export const customerTemplateRoutes = [
  { path: "/", src: "/template-17/index.html", title: "Home" },
  { path: "/home", src: "/template-17/index.html", title: "Home" },
  { path: "/index-user", src: "/template-17/index-user.html", title: "Home User" },

  { path: "/login", src: "/template-17/login.html", title: "Login" },
  { path: "/register-static", src: "/template-17/login.html?login=register", title: "Register Static" },
  { path: "/about", src: "/template-17/about.html", title: "About" },
  { path: "/contact-us", src: "/template-17/contact-us.html", title: "Contact Us" },
  { path: "/faq", src: "/template-17/faq.html", title: "FAQ" },
  { path: "/feedback", src: "/template-17/feedback.html", title: "Feedback" },
  { path: "/privacy-policy", src: "/template-17/privacy-policy.html", title: "Privacy Policy" },
  { path: "/terms-of-use", src: "/template-17/terms-of-use.html", title: "Terms of Use" },
  { path: "/how-to", src: "/template-17/how-to.html", title: "How To" },

  { path: "/all-category", src: "/template-17/all-category.html", title: "All Category" },
  { path: "/all-listing", src: "/template-17/all-listing.html", title: "All Listing" },
  { path: "/listing-details", src: "/template-17/listing-details.html", title: "Listing Details" },

  { path: "/blog-posts", src: "/template-17/blog-posts.html", title: "Blog Posts" },
  { path: "/blog-details", src: "/template-17/blog-details.html", title: "Blog Details" },
  { path: "/create-new-blog-post", src: "/template-17/create-new-blog-post.html", title: "Create New Blog Post" },
  { path: "/edit-blog-post", src: "/template-17/edit-blog-post.html", title: "Edit Blog Post" },

  { path: "/events", src: "/template-17/events.html", title: "Events" },
  { path: "/event-details", src: "/template-17/event-details.html", title: "Event Details" },
  { path: "/create-new-event", src: "/template-17/create-new-event.html", title: "Create New Event" },
  { path: "/edit-event", src: "/template-17/edit-event.html", title: "Edit Event" },

  { path: "/products", src: "/template-17/products.html", title: "Products" },
  { path: "/product-details", src: "/template-17/product-details.html", title: "Product Details" },
  { path: "/add-new-product", src: "/template-17/add-new-product.html", title: "Add New Product" },
  { path: "/edit-product", src: "/template-17/edit-product.html", title: "Edit Product" },

  { path: "/coupons", src: "/template-17/coupons.html", title: "Coupons" },
  { path: "/add-coupons", src: "/template-17/add-coupons.html", title: "Add Coupons" },
  { path: "/edit-coupon", src: "/template-17/edit-coupon.html", title: "Edit Coupon" },

  { path: "/buy-points", src: "/template-17/buy-points.html", title: "Buy Points" },
  { path: "/pricing-details", src: "/template-17/pricing-details.html", title: "Pricing Details" },
  { path: "/promote-business", src: "/template-17/promote-business.html", title: "Promote Business" },

  { path: "/community", src: "/template-17/community.html", title: "Community" },
  { path: "/search-results", src: "/template-17/search-results.html", title: "Search Results" },
  { path: "/company-profile", src: "/template-17/company-profile.html", title: "Company Profile" },
  { path: "/company-profile-edit", src: "/template-17/company-profile-edit.html", title: "Company Profile Edit" },
  { path: "/profile", src: "/template-17/profile.html", title: "Profile" },
  { path: "/profile-job-user", src: "/template-17/profile-job-user.html", title: "Profile Job User" },

  { path: "/ad-details", src: "/template-17/ad-details.html", title: "Ad Details" },
  { path: "/post-your-ads", src: "/template-17/post-your-ads.html", title: "Post Your Ads" },

  { path: "/add-listing/start", src: "/template-17/add-listing-start.html", title: "Add Listing Start" },
  { path: "/add-listing/step-1", src: "/template-17/add-listing-step-1.html", title: "Add Listing Step 1" },
  { path: "/add-listing/step-2", src: "/template-17/add-listing-step-2.html", title: "Add Listing Step 2" },
  { path: "/add-listing/step-3", src: "/template-17/add-listing-step-3.html", title: "Add Listing Step 3" },
  { path: "/add-listing/step-4", src: "/template-17/add-listing-step-4.html", title: "Add Listing Step 4" },
  { path: "/add-listing/step-5", src: "/template-17/add-listing-step-5.html", title: "Add Listing Step 5" },
  { path: "/add-listing/step-6", src: "/template-17/add-listing-step-6.html", title: "Add Listing Step 6" },

  { path: "/edit-listing/step-1", src: "/template-17/edit-listing-step-1.html", title: "Edit Listing Step 1" },
  { path: "/edit-listing/step-2", src: "/template-17/edit-listing-step-2.html", title: "Edit Listing Step 2" },
  { path: "/edit-listing/step-3", src: "/template-17/edit-listing-step-3.html", title: "Edit Listing Step 3" },
  { path: "/edit-listing/step-4", src: "/template-17/edit-listing-step-4.html", title: "Edit Listing Step 4" },
  { path: "/edit-listing/step-5", src: "/template-17/edit-listing-step-5.html", title: "Edit Listing Step 5" },
  { path: "/edit-listing/step-6", src: "/template-17/edit-listing-step-6.html", title: "Edit Listing Step 6" },

  { path: "/create-job", src: "/template-17/create-job.html", title: "Create Job" },
  { path: "/edit-job", src: "/template-17/edit-job.html", title: "Edit Job" },
  { path: "/delete-job", src: "/template-17/delete-job.html", title: "Delete Job" },
  { path: "/create-job-seeker-profile", src: "/template-17/create-job-seeker-profile.html", title: "Create Job Seeker Profile" },
  { path: "/create-service-expert-profile", src: "/template-17/create-service-expert-profile.html", title: "Create Service Expert Profile" },

  { path: "/dashboard", src: "/template-17/dashboard.html", title: "Dashboard" },
  { path: "/dashboard/all-listing", src: "/template-17/db-all-listing.html", title: "Dashboard All Listing" },
  { path: "/dashboard/ad-posts", src: "/template-17/db-ad-posts.html", title: "Dashboard Ad Posts" },
  { path: "/dashboard/all-users", src: "/template-17/db-all-users.html", title: "Dashboard All Users" },
  { path: "/dashboard/blog-posts", src: "/template-17/db-blog-posts.html", title: "Dashboard Blog Posts" },
  { path: "/dashboard/coupons", src: "/template-17/db-coupons.html", title: "Dashboard Coupons" },
  { path: "/dashboard/enquiry", src: "/template-17/db-enquiry.html", title: "Dashboard Enquiry" },
  { path: "/dashboard/events", src: "/template-17/db-events.html", title: "Dashboard Events" },
  { path: "/dashboard/followings", src: "/template-17/db-followings.html", title: "Dashboard Followings" },
  { path: "/dashboard/invoice", src: "/template-17/db-invoice-all.html", title: "Dashboard Invoice" },
  { path: "/dashboard/jobs", src: "/template-17/db-jobs.html", title: "Dashboard Jobs" },
  { path: "/dashboard/jobs-applicant-profile", src: "/template-17/db-jobs-applicant-profile.html", title: "Dashboard Jobs Applicant Profile" },
  { path: "/dashboard/like-listings", src: "/template-17/db-like-listings.html", title: "Dashboard Like Listings" },
  { path: "/dashboard/my-profile", src: "/template-17/db-my-profile.html", title: "Dashboard My Profile" },
  { path: "/dashboard/my-profile-edit", src: "/template-17/db-my-profile-edit.html", title: "Dashboard My Profile Edit" },
  { path: "/dashboard/my-service-bookings", src: "/template-17/db-my-service-bookings.html", title: "Dashboard My Service Bookings" },
  { path: "/dashboard/notifications", src: "/template-17/db-notifications.html", title: "Dashboard Notifications" },
  { path: "/dashboard/payment", src: "/template-17/db-payment.html", title: "Dashboard Payment" },
  { path: "/dashboard/plan-change", src: "/template-17/db-plan-change.html", title: "Dashboard Plan Change" },
  { path: "/dashboard/point-history", src: "/template-17/db-point-history.html", title: "Dashboard Point History" },
  { path: "/dashboard/post-ads", src: "/template-17/db-post-ads.html", title: "Dashboard Post Ads" },
  { path: "/dashboard/products", src: "/template-17/db-products.html", title: "Dashboard Products" },
  { path: "/dashboard/promote", src: "/template-17/db-promote.html", title: "Dashboard Promote" },
  { path: "/dashboard/review", src: "/template-17/db-review.html", title: "Dashboard Review" },
  { path: "/dashboard/seo", src: "/template-17/db-seo.html", title: "Dashboard SEO" },
  { path: "/dashboard/service-expert", src: "/template-17/db-service-expert.html", title: "Dashboard Service Expert" },
  { path: "/dashboard/setting", src: "/template-17/db-setting.html", title: "Dashboard Setting" },
  { path: "/dashboard/user-applied-jobs", src: "/template-17/db-user-applied-jobs.html", title: "Dashboard User Applied Jobs" },

  { path: "/demo", src: "/template-17/demo.html", title: "Demo" },
  { path: "/ebook", src: "/template-17/ebook.html", title: "Ebook" },
  { path: "/404", src: "/template-17/404.html", title: "404" }
];