import type { ListingCategoryOption } from "../api/listingCategoriesApi";

export const supportedListingCategoryNames = [
  "Real Estate",
  "Restaurants & Food",
  "Vehicles",
  "Care Services",
  "Events & Tickets",
  "Roommates & Rentals",
  "Jobs",
  "Electronics & Appliances",
  "Furniture & Home",
  "Pets & Animals",
] as const;

const supportedListingCategoryNameSet = new Set<string>(supportedListingCategoryNames);

export const fallbackListingCategoryTree: ListingCategoryOption[] = [
  {
    id: 1,
    name: "Real Estate",
    slug: "real-estate",
    subCategories: [
      { id: 101, name: "For Sale", slug: "for-sale", detailedCategories: [
        { id: 1001, name: "Apartments / Flats", slug: "for-sale-apartments-flats" },
        { id: 1002, name: "Independent Houses", slug: "independent-houses" },
        { id: 1003, name: "Villas", slug: "for-sale-villas" },
        { id: 1004, name: "Builder Floors", slug: "for-sale-builder-floors" },
        { id: 1005, name: "Townhouses", slug: "townhouses" },
        { id: 1006, name: "Condos", slug: "for-sale-condos" },
        { id: 1007, name: "Duplex / Triplex", slug: "duplex-triplex" },
        { id: 1008, name: "Farm Houses", slug: "farm-houses" },
        { id: 1009, name: "Mobile Homes", slug: "mobile-homes" },
        { id: 1010, name: "Land / Plots", slug: "for-sale-land-plots" },
      ] },
      { id: 102, name: "For Rent", slug: "for-rent", detailedCategories: [
        { id: 1011, name: "Apartments", slug: "for-rent-apartments" },
        { id: 1012, name: "Houses", slug: "for-rent-houses" },
        { id: 1013, name: "Villas", slug: "for-rent-villas" },
        { id: 1014, name: "Condos", slug: "for-rent-condos" },
        { id: 1015, name: "Studio Apartments", slug: "studio-apartments" },
        { id: 1016, name: "Basement Rentals", slug: "basement-rentals" },
        { id: 1017, name: "Shared Rooms", slug: "for-rent-shared-rooms" },
        { id: 1018, name: "Single Rooms", slug: "for-rent-single-rooms" },
        { id: 1019, name: "Entire Homes", slug: "entire-homes" },
      ] },
      { id: 103, name: "PG / Co-living", slug: "pg-co-living", detailedCategories: [
        { id: 1020, name: "PG Accommodation", slug: "pg-accommodation" },
        { id: 1021, name: "Shared Accommodation", slug: "shared-accommodation" },
        { id: 1022, name: "Co-living Spaces", slug: "co-living-spaces" },
        { id: 1023, name: "Student Housing", slug: "student-housing" },
        { id: 1024, name: "Working Professionals Housing", slug: "working-professionals-housing" },
      ] },
      { id: 104, name: "Commercial", slug: "commercial", detailedCategories: [
        { id: 1025, name: "Office Spaces", slug: "commercial-office-spaces" },
        { id: 1026, name: "Coworking Spaces", slug: "coworking-spaces" },
        { id: 1027, name: "Shops / Retail Stores", slug: "shops-retail-stores" },
        { id: 1028, name: "Warehouses / Godowns", slug: "warehouses-godowns" },
        { id: 1029, name: "Industrial Spaces", slug: "industrial-spaces" },
        { id: 1030, name: "Commercial Land", slug: "commercial-land" },
        { id: 1031, name: "Restaurants / Hospitality Spaces", slug: "restaurants-hospitality-spaces" },
      ] },
      { id: 105, name: "Vacation Rentals", slug: "vacation-rentals", detailedCategories: [
        { id: 1032, name: "Vacation Homes", slug: "vacation-homes" },
        { id: 1033, name: "Airbnb Rentals", slug: "airbnb-rentals" },
        { id: 1034, name: "Beach Houses", slug: "beach-houses" },
        { id: 1035, name: "Cabins / Cottages", slug: "cabins-cottages" },
        { id: 1036, name: "Resorts & Retreats", slug: "resorts-retreats" },
      ] },
      { id: 106, name: "New Projects / New Construction", slug: "new-projects-new-construction", detailedCategories: [
        { id: 1037, name: "New Apartments", slug: "new-apartments" },
        { id: 1038, name: "Under Construction Projects", slug: "under-construction-projects" },
        { id: 1039, name: "Ready-to-Move Homes", slug: "ready-to-move-homes" },
        { id: 1040, name: "Builder Projects", slug: "builder-projects" },
        { id: 1041, name: "Gated Communities", slug: "gated-communities" },
      ] },
      { id: 107, name: "Real Estate Services", slug: "real-estate-services", detailedCategories: [
        { id: 1042, name: "Real Estate Agents", slug: "real-estate-agents" },
        { id: 1043, name: "Property Management", slug: "property-management" },
        { id: 1044, name: "Home Inspection", slug: "home-inspection" },
        { id: 1045, name: "Interior Designers", slug: "interior-designers" },
        { id: 1046, name: "Movers & Packers", slug: "movers-packers" },
        { id: 1047, name: "Mortgage & Loan Services", slug: "mortgage-loan-services" },
      ] },
    ],
  },
  {
    id: 13,
    name: "Roommates & Rentals",
    slug: "roommates-rentals",
    subCategories: [
      { id: 1301, name: "Roommates Wanted", slug: "roommates-wanted", detailedCategories: [
        { id: 13001, name: "Male Roommate Wanted", slug: "male-roommate-wanted" },
        { id: 13002, name: "Female Roommate Wanted", slug: "female-roommate-wanted" },
        { id: 13003, name: "Student Roommate Wanted", slug: "student-roommate-wanted" },
        { id: 13004, name: "Professional Roommate Wanted", slug: "professional-roommate-wanted" },
        { id: 13005, name: "Family Shared Accommodation", slug: "family-shared-accommodation" },
      ] },
      { id: 1302, name: "Rooms for Rent", slug: "rooms-for-rent", detailedCategories: [
        { id: 13006, name: "Private Room", slug: "private-room-rental" },
        { id: 13007, name: "Shared Room", slug: "shared-room-rental" },
        { id: 13008, name: "Furnished Room", slug: "furnished-room-rental" },
        { id: 13009, name: "Unfurnished Room", slug: "unfurnished-room-rental" },
        { id: 13010, name: "Master Bedroom Rental", slug: "master-bedroom-rental" },
      ] },
      { id: 1303, name: "Shared Apartments", slug: "shared-apartments", detailedCategories: [
        { id: 13011, name: "1 Bedroom Shared Apartment", slug: "one-bedroom-shared-apartment" },
        { id: 13012, name: "2 Bedroom Shared Apartment", slug: "two-bedroom-shared-apartment" },
        { id: 13013, name: "Luxury Apartment Sharing", slug: "luxury-apartment-sharing" },
        { id: 13014, name: "Student Apartment Sharing", slug: "student-apartment-sharing" },
      ] },
      { id: 1304, name: "Shared Houses", slug: "shared-houses", detailedCategories: [
        { id: 13015, name: "Single Family House Sharing", slug: "single-family-house-sharing" },
        { id: 13016, name: "Townhouse Sharing", slug: "townhouse-sharing" },
        { id: 13017, name: "Duplex Sharing", slug: "duplex-sharing" },
        { id: 13018, name: "Basement Rental", slug: "basement-room-rental" },
      ] },
      { id: 1305, name: "Paying Guest (PG) Accommodation", slug: "paying-guest-pg-accommodation", detailedCategories: [
        { id: 13019, name: "PG Private Room", slug: "pg-private-room" },
        { id: 13020, name: "PG Shared Room", slug: "pg-shared-room" },
        { id: 13021, name: "PG With Meals", slug: "pg-with-meals" },
        { id: 13022, name: "PG Near University", slug: "pg-near-university" },
      ] },
      { id: 1306, name: "Student Housing", slug: "student-housing", detailedCategories: [
        { id: 13023, name: "University Housing", slug: "university-housing" },
        { id: 13024, name: "Off-Campus Housing", slug: "off-campus-housing" },
        { id: 13025, name: "Dormitory Accommodation", slug: "dormitory-accommodation" },
        { id: 13026, name: "International Student Housing", slug: "international-student-housing" },
      ] },
      { id: 1307, name: "Temporary & Short-Term Rentals", slug: "temporary-short-term-rentals", detailedCategories: [
        { id: 13027, name: "Weekly Rentals", slug: "weekly-rentals" },
        { id: 13028, name: "Monthly Rentals", slug: "monthly-rentals" },
        { id: 13029, name: "Temporary Relocation Housing", slug: "temporary-relocation-housing" },
        { id: 13030, name: "Internship Accommodation", slug: "internship-accommodation" },
      ] },
      { id: 1308, name: "Sublease & Lease Transfer", slug: "sublease-lease-transfer", detailedCategories: [
        { id: 13031, name: "Apartment Sublease", slug: "apartment-sublease" },
        { id: 13032, name: "House Sublease", slug: "house-sublease" },
        { id: 13033, name: "Lease Takeover", slug: "lease-takeover" },
        { id: 13034, name: "Lease Assignment", slug: "lease-assignment" },
      ] },
      { id: 1309, name: "Co-Living Spaces", slug: "co-living-spaces", detailedCategories: [
        { id: 13035, name: "Shared Living Communities", slug: "shared-living-communities" },
        { id: 13036, name: "Managed Co-Living", slug: "managed-co-living" },
        { id: 13037, name: "Premium Co-Living Spaces", slug: "premium-co-living-spaces" },
      ] },
      { id: 1310, name: "Vacation & Corporate Housing", slug: "vacation-corporate-housing", detailedCategories: [
        { id: 13038, name: "Corporate Apartments", slug: "corporate-apartments" },
        { id: 13039, name: "Executive Housing", slug: "executive-housing" },
        { id: 13040, name: "Vacation Rentals", slug: "vacation-rentals-roommates" },
        { id: 13041, name: "Business Traveler Housing", slug: "business-traveler-housing" },
      ] },
    ],
  },
  {
    id: 14,
    name: "Jobs",
    slug: "jobs",
    subCategories: [
      { id: 1401, name: "Information Technology (IT)", slug: "jobs-information-technology-it", detailedCategories: [
        { id: 14001, name: "Software Developer", slug: "jobs-software-developer" },
        { id: 14002, name: "Full Stack Developer", slug: "jobs-full-stack-developer" },
        { id: 14003, name: "Front-End Developer", slug: "jobs-front-end-developer" },
        { id: 14004, name: "Back-End Developer", slug: "jobs-back-end-developer" },
        { id: 14005, name: "Mobile App Developer", slug: "jobs-mobile-app-developer" },
        { id: 14006, name: "Data Engineer", slug: "jobs-data-engineer" },
        { id: 14007, name: "Data Scientist", slug: "jobs-data-scientist" },
        { id: 14008, name: "AI / ML Engineer", slug: "jobs-ai-ml-engineer" },
        { id: 14009, name: "DevOps Engineer", slug: "jobs-devops-engineer" },
        { id: 14010, name: "Cloud Engineer", slug: "jobs-cloud-engineer" },
        { id: 14011, name: "Cybersecurity Analyst", slug: "jobs-cybersecurity-analyst" },
        { id: 14012, name: "QA Engineer", slug: "jobs-qa-engineer" },
        { id: 14013, name: "Business Analyst", slug: "jobs-business-analyst" },
        { id: 14014, name: "Project Manager", slug: "jobs-project-manager" },
      ] },
      { id: 1402, name: "Engineering", slug: "jobs-engineering", detailedCategories: [
        { id: 14015, name: "Mechanical Engineer", slug: "jobs-mechanical-engineer" },
        { id: 14016, name: "Electrical Engineer", slug: "jobs-electrical-engineer" },
        { id: 14017, name: "Civil Engineer", slug: "jobs-civil-engineer" },
        { id: 14018, name: "Embedded Engineer", slug: "jobs-embedded-engineer" },
        { id: 14019, name: "Industrial Engineer", slug: "jobs-industrial-engineer" },
        { id: 14020, name: "Robotics Engineer", slug: "jobs-robotics-engineer" },
      ] },
      { id: 1403, name: "Healthcare", slug: "jobs-healthcare", detailedCategories: [
        { id: 14021, name: "Registered Nurse (RN)", slug: "jobs-registered-nurse-rn" },
        { id: 14022, name: "Physician", slug: "jobs-physician" },
        { id: 14023, name: "Medical Assistant", slug: "jobs-medical-assistant" },
        { id: 14024, name: "Physical Therapist", slug: "jobs-physical-therapist" },
        { id: 14025, name: "Pharmacist", slug: "jobs-pharmacist" },
        { id: 14026, name: "Caregiver", slug: "jobs-caregiver" },
      ] },
      { id: 1404, name: "Finance & Accounting", slug: "jobs-finance-accounting", detailedCategories: [
        { id: 14027, name: "Accountant", slug: "jobs-accountant" },
        { id: 14028, name: "Financial Analyst", slug: "jobs-financial-analyst" },
        { id: 14029, name: "Auditor", slug: "jobs-auditor" },
        { id: 14030, name: "Tax Consultant", slug: "jobs-tax-consultant" },
        { id: 14031, name: "Payroll Specialist", slug: "jobs-payroll-specialist" },
      ] },
      { id: 1405, name: "Sales & Marketing", slug: "jobs-sales-marketing", detailedCategories: [
        { id: 14032, name: "Sales Executive", slug: "jobs-sales-executive" },
        { id: 14033, name: "Account Manager", slug: "jobs-account-manager" },
        { id: 14034, name: "Digital Marketing Specialist", slug: "jobs-digital-marketing-specialist" },
        { id: 14035, name: "SEO Specialist", slug: "jobs-seo-specialist" },
        { id: 14036, name: "Social Media Manager", slug: "jobs-social-media-manager" },
      ] },
      { id: 1406, name: "Customer Service", slug: "jobs-customer-service", detailedCategories: [
        { id: 14037, name: "Call Center Representative", slug: "jobs-call-center-representative" },
        { id: 14038, name: "Technical Support", slug: "jobs-technical-support" },
        { id: 14039, name: "Customer Success Manager", slug: "jobs-customer-success-manager" },
      ] },
      { id: 1407, name: "Education & Training", slug: "jobs-education-training", detailedCategories: [
        { id: 14040, name: "Teacher", slug: "jobs-teacher" },
        { id: 14041, name: "Tutor", slug: "jobs-tutor" },
        { id: 14042, name: "Trainer", slug: "jobs-trainer" },
        { id: 14043, name: "Professor", slug: "jobs-professor" },
      ] },
      { id: 1408, name: "Hospitality & Tourism", slug: "jobs-hospitality-tourism", detailedCategories: [
        { id: 14044, name: "Hotel Manager", slug: "jobs-hotel-manager" },
        { id: 14045, name: "Chef", slug: "jobs-chef" },
        { id: 14046, name: "Restaurant Staff", slug: "jobs-restaurant-staff" },
        { id: 14047, name: "Travel Consultant", slug: "jobs-travel-consultant" },
      ] },
      { id: 1409, name: "Logistics & Transportation", slug: "jobs-logistics-transportation", detailedCategories: [
        { id: 14048, name: "Truck Driver", slug: "jobs-truck-driver" },
        { id: 14049, name: "Delivery Driver", slug: "jobs-delivery-driver" },
        { id: 14050, name: "Warehouse Associate", slug: "jobs-warehouse-associate" },
        { id: 14051, name: "Supply Chain Manager", slug: "jobs-supply-chain-manager" },
      ] },
      { id: 1410, name: "Construction & Skilled Trades", slug: "jobs-construction-skilled-trades", detailedCategories: [
        { id: 14052, name: "Electrician", slug: "jobs-electrician" },
        { id: 14053, name: "Plumber", slug: "jobs-plumber" },
        { id: 14054, name: "Carpenter", slug: "jobs-carpenter" },
        { id: 14055, name: "HVAC Technician", slug: "jobs-hvac-technician" },
      ] },
      { id: 1411, name: "Retail & E-Commerce", slug: "jobs-retail-e-commerce", detailedCategories: [
        { id: 14056, name: "Store Manager", slug: "jobs-store-manager" },
        { id: 14057, name: "Cashier", slug: "jobs-cashier" },
        { id: 14058, name: "Inventory Manager", slug: "jobs-inventory-manager" },
        { id: 14059, name: "E-Commerce Executive", slug: "jobs-e-commerce-executive" },
      ] },
      { id: 1412, name: "Human Resources", slug: "jobs-human-resources", detailedCategories: [
        { id: 14060, name: "HR Executive", slug: "jobs-hr-executive" },
        { id: 14061, name: "Recruiter", slug: "jobs-recruiter" },
        { id: 14062, name: "Talent Acquisition Specialist", slug: "jobs-talent-acquisition-specialist" },
        { id: 14063, name: "HR Manager", slug: "jobs-hr-manager" },
      ] },
      { id: 1413, name: "Legal Services", slug: "jobs-legal-services", detailedCategories: [
        { id: 14064, name: "Attorney", slug: "jobs-attorney" },
        { id: 14065, name: "Paralegal", slug: "jobs-paralegal" },
        { id: 14066, name: "Legal Assistant", slug: "jobs-legal-assistant" },
      ] },
      { id: 1414, name: "Government & Public Sector", slug: "jobs-government-public-sector", detailedCategories: [
        { id: 14067, name: "Government Administration", slug: "jobs-government-administration" },
        { id: 14068, name: "Public Sector Analyst", slug: "jobs-public-sector-analyst" },
        { id: 14069, name: "Public Works Staff", slug: "jobs-public-works-staff" },
      ] },
      { id: 1415, name: "Freelance & Remote Jobs", slug: "jobs-freelance-remote-jobs", detailedCategories: [
        { id: 14070, name: "Freelance Developer", slug: "jobs-freelance-developer" },
        { id: 14071, name: "Virtual Assistant", slug: "jobs-virtual-assistant" },
        { id: 14072, name: "Content Writer", slug: "jobs-content-writer" },
        { id: 14073, name: "Graphic Designer", slug: "jobs-graphic-designer" },
      ] },
      { id: 1416, name: "Internships & Entry-Level Jobs", slug: "jobs-internships-entry-level-jobs", detailedCategories: [
        { id: 14074, name: "Student Internship", slug: "jobs-student-internship" },
        { id: 14075, name: "Graduate Trainee", slug: "jobs-graduate-trainee" },
        { id: 14076, name: "Entry-Level Associate", slug: "jobs-entry-level-associate" },
      ] },
    ],
  },
  {
    id: 2,
    name: "Vehicles",
    slug: "vehicles",
    subCategories: [
      { id: 201, name: "Cars", slug: "cars", detailedCategories: [
        { id: 2001, name: "Sedan", slug: "sedan" },
        { id: 2002, name: "Hatchback", slug: "hatchback" },
        { id: 2003, name: "Coupe", slug: "coupe" },
        { id: 2004, name: "Convertible", slug: "convertible" },
        { id: 2005, name: "Wagon", slug: "wagon" },
      ] },
      { id: 202, name: "SUVs & Crossovers", slug: "suvs-crossovers", detailedCategories: [
        { id: 2006, name: "Compact SUV", slug: "compact-suv" },
        { id: 2007, name: "Mid-Size SUV", slug: "mid-size-suv" },
        { id: 2008, name: "Full-Size SUV", slug: "full-size-suv" },
        { id: 2009, name: "Luxury SUV", slug: "luxury-suv" },
      ] },
      { id: 203, name: "Trucks", slug: "trucks", detailedCategories: [
        { id: 2010, name: "Pickup Trucks", slug: "pickup-trucks" },
        { id: 2011, name: "Heavy Duty Trucks", slug: "heavy-duty-trucks" },
        { id: 2012, name: "Utility Trucks", slug: "utility-trucks" },
      ] },
      { id: 204, name: "Vans & Minivans", slug: "vans-minivans", detailedCategories: [
        { id: 2013, name: "Passenger Vans", slug: "passenger-vans" },
        { id: 2014, name: "Cargo Vans", slug: "cargo-vans" },
        { id: 2015, name: "Family Minivans", slug: "family-minivans" },
      ] },
      { id: 205, name: "Motorcycles & Scooters", slug: "motorcycles-scooters", detailedCategories: [
        { id: 2016, name: "Sport Bikes", slug: "sport-bikes" },
        { id: 2017, name: "Cruisers", slug: "cruisers" },
        { id: 2018, name: "Touring Bikes", slug: "touring-bikes" },
        { id: 2019, name: "Electric Scooters", slug: "electric-scooters" },
      ] },
      { id: 206, name: "Electric Vehicles (EVs)", slug: "electric-vehicles-evs", detailedCategories: [
        { id: 2020, name: "Electric Cars", slug: "electric-cars" },
        { id: 2021, name: "Electric SUVs", slug: "electric-suvs" },
        { id: 2022, name: "Electric Trucks", slug: "electric-trucks" },
      ] },
      { id: 207, name: "Hybrid Vehicles", slug: "hybrid-vehicles", detailedCategories: [
        { id: 2023, name: "Hybrid Cars", slug: "hybrid-cars" },
        { id: 2024, name: "Hybrid SUVs", slug: "hybrid-suvs" },
        { id: 2025, name: "Plug-in Hybrids", slug: "plug-in-hybrids" },
      ] },
      { id: 208, name: "Commercial Vehicles", slug: "commercial-vehicles", detailedCategories: [
        { id: 2026, name: "Delivery Vans", slug: "delivery-vans" },
        { id: 2027, name: "Box Trucks", slug: "box-trucks" },
        { id: 2028, name: "Fleet Vehicles", slug: "fleet-vehicles" },
      ] },
      { id: 209, name: "RVs & Campers", slug: "rvs-campers", detailedCategories: [
        { id: 2029, name: "Motorhomes", slug: "motorhomes" },
        { id: 2030, name: "Travel Trailers", slug: "travel-trailers" },
        { id: 2031, name: "Fifth Wheels", slug: "fifth-wheels" },
        { id: 2032, name: "Camper Vans", slug: "camper-vans" },
      ] },
      { id: 210, name: "Boats & Watercraft", slug: "boats-watercraft", detailedCategories: [
        { id: 2033, name: "Fishing Boats", slug: "fishing-boats" },
        { id: 2034, name: "Pontoon Boats", slug: "pontoon-boats" },
        { id: 2035, name: "Jet Skis", slug: "jet-skis" },
        { id: 2036, name: "Yachts", slug: "yachts" },
      ] },
      { id: 211, name: "Auto Parts & Accessories", slug: "auto-parts-accessories", detailedCategories: [
        { id: 2037, name: "Engine Parts", slug: "engine-parts" },
        { id: 2038, name: "Batteries", slug: "batteries" },
        { id: 2039, name: "Audio Systems", slug: "audio-systems" },
        { id: 2040, name: "Floor Mats", slug: "floor-mats" },
        { id: 2041, name: "Performance Parts", slug: "performance-parts" },
      ] },
      { id: 212, name: "Tires & Wheels", slug: "tires-wheels", detailedCategories: [
        { id: 2042, name: "All Season Tires", slug: "all-season-tires" },
        { id: 2043, name: "Winter Tires", slug: "winter-tires" },
        { id: 2044, name: "Alloy Wheels", slug: "alloy-wheels" },
        { id: 2045, name: "Custom Wheels", slug: "custom-wheels" },
      ] },
      { id: 213, name: "Vehicle Rentals", slug: "vehicle-rentals", detailedCategories: [
        { id: 2046, name: "Daily Rentals", slug: "daily-rentals" },
        { id: 2047, name: "Weekly Rentals", slug: "weekly-rentals" },
        { id: 2048, name: "Luxury Rentals", slug: "luxury-rentals" },
        { id: 2049, name: "Corporate Rentals", slug: "corporate-rentals" },
      ] },
      { id: 214, name: "Auto Services & Repair", slug: "auto-services-repair", detailedCategories: [
        { id: 2050, name: "Oil Change", slug: "oil-change" },
        { id: 2051, name: "Brake Service", slug: "brake-service" },
        { id: 2052, name: "Tire Service", slug: "tire-service" },
        { id: 2053, name: "Body Repair", slug: "body-repair" },
        { id: 2054, name: "Car Wash & Detailing", slug: "car-wash-detailing" },
      ] },
      { id: 215, name: "Car Dealers", slug: "car-dealers", detailedCategories: [
        { id: 2055, name: "New Car Dealers", slug: "new-car-dealers" },
        { id: 2056, name: "Used Car Dealers", slug: "used-car-dealers" },
        { id: 2057, name: "Certified Dealers", slug: "certified-dealers" },
      ] },
    ],
  },
  {
    id: 11,
    name: "Restaurants & Food",
    slug: "restaurants-food",
    subCategories: [
      { id: 1101, name: "Restaurants (Dine-In)", slug: "restaurant", detailedCategories: [
        { id: 11001, name: "Fine Dining Restaurants", slug: "fine-dining-restaurants" },
        { id: 11002, name: "Casual Dining Restaurants", slug: "casual-dining-restaurants" },
        { id: 11003, name: "Family Restaurants", slug: "family-restaurants" },
        { id: 11004, name: "Buffet Restaurants", slug: "buffet-restaurants" },
        { id: 11005, name: "Multi-Cuisine Restaurants", slug: "multi-cuisine-restaurants" },
        { id: 11006, name: "Ethnic Restaurants", slug: "ethnic-restaurants" },
        { id: 11007, name: "Seafood Restaurants", slug: "seafood-restaurants" },
        { id: 11008, name: "Steak Houses", slug: "steak-houses" },
      ] },
      { id: 1102, name: "Fast Food & Takeaway", slug: "fast-food-takeaway", detailedCategories: [
        { id: 11009, name: "Burger Outlets", slug: "burger-outlets" },
        { id: 11010, name: "Pizza Restaurants", slug: "pizza-restaurants" },
        { id: 11011, name: "Sandwich Shops", slug: "sandwich-shops" },
        { id: 11012, name: "Fried Chicken Outlets", slug: "fried-chicken-outlets" },
        { id: 11013, name: "Taco / Mexican Shops", slug: "taco-mexican-shops" },
        { id: 11014, name: "Hot Dog Shops", slug: "hot-dog-shops" },
        { id: 11015, name: "Grab & Go Meals", slug: "grab-go-meals" },
      ] },
      { id: 1103, name: "Cafes & Bakeries", slug: "cafe", detailedCategories: [
        { id: 11016, name: "Coffee Shops", slug: "coffee-shops" },
        { id: 11017, name: "Tea Cafes", slug: "tea-cafes" },
        { id: 11018, name: "Bakeries", slug: "bakeries" },
        { id: 11019, name: "Cake Shops", slug: "cake-shops" },
        { id: 11020, name: "Dessert Parlors", slug: "dessert-parlors" },
        { id: 11021, name: "Ice Cream Shops", slug: "ice-cream-shops" },
        { id: 11022, name: "Juice & Smoothie Bars", slug: "juice-smoothie-bars" },
      ] },
      { id: 1104, name: "Cloud Kitchen / Delivery Only", slug: "cloud-kitchen", detailedCategories: [
        { id: 11023, name: "Home Kitchens", slug: "home-kitchens" },
        { id: 11024, name: "Delivery-only Restaurants", slug: "delivery-only-restaurants" },
        { id: 11025, name: "Tiffin Services", slug: "tiffin-services" },
        { id: 11026, name: "Meal Prep Services", slug: "meal-prep-services" },
        { id: 11027, name: "Healthy / Diet Meal Providers", slug: "healthy-diet-meal-providers" },
        { id: 11028, name: "Keto / Vegan Meal Providers", slug: "keto-vegan-meal-providers" },
      ] },
      { id: 1105, name: "Catering Services", slug: "catering", detailedCategories: [
        { id: 11029, name: "Wedding Catering", slug: "wedding-catering" },
        { id: 11030, name: "Corporate Catering", slug: "corporate-catering" },
        { id: 11031, name: "Party Catering", slug: "party-catering" },
        { id: 11032, name: "Event Catering", slug: "event-catering" },
        { id: 11033, name: "Packed Meal Services", slug: "packed-meal-services" },
        { id: 11034, name: "Live Cooking Stations", slug: "live-cooking-stations" },
      ] },
      { id: 1106, name: "Bars & Beverages", slug: "bars-beverages", detailedCategories: [
        { id: 11035, name: "Bars", slug: "bars" },
        { id: 11036, name: "Pubs", slug: "pubs" },
        { id: 11037, name: "Lounges", slug: "lounges" },
        { id: 11038, name: "Wine Bars", slug: "wine-bars" },
        { id: 11039, name: "Cocktail Bars", slug: "cocktail-bars" },
        { id: 11040, name: "Sports Bars", slug: "sports-bars" },
        { id: 11041, name: "Hookah Lounges", slug: "hookah-lounges" },
      ] },
      { id: 1107, name: "Food Trucks & Pop-ups", slug: "food-trucks-pop-ups", detailedCategories: [
        { id: 11042, name: "Food Trucks", slug: "food-trucks" },
        { id: 11043, name: "Street Food Vendors", slug: "street-food-vendors" },
        { id: 11044, name: "Pop-up Kitchens", slug: "pop-up-kitchens" },
        { id: 11045, name: "Festival Food Stalls", slug: "festival-food-stalls" },
        { id: 11046, name: "Mobile Coffee Trucks", slug: "mobile-coffee-trucks" },
      ] },
      { id: 1108, name: "Grocery & Specialty Food Stores", slug: "grocery-specialty-food-stores", detailedCategories: [
        { id: 11047, name: "Indian Grocery Stores", slug: "indian-grocery-stores" },
        { id: 11048, name: "Asian Markets", slug: "asian-markets" },
        { id: 11049, name: "Organic Food Stores", slug: "organic-food-stores" },
        { id: 11050, name: "Meat Shops", slug: "meat-shops" },
        { id: 11051, name: "Seafood Markets", slug: "seafood-markets" },
        { id: 11052, name: "Bakery Supply Stores", slug: "bakery-supply-stores" },
      ] },
    ],
  },
  {
    id: 3,
    name: "Electronics & Appliances",
    slug: "electronics-appliances",
    subCategories: [
      { id: 301, name: "Mobile Phones & Tablets", slug: "mobile-phones-tablets", detailedCategories: [
        { id: 3001, name: "Smartphones", slug: "smartphones" },
        { id: 3002, name: "Feature Phones", slug: "feature-phones" },
        { id: 3003, name: "Tablets", slug: "tablets" },
        { id: 3004, name: "iPads", slug: "ipads" },
        { id: 3005, name: "Smart Watches", slug: "mobile-smart-watches" },
        { id: 3006, name: "Mobile Accessories", slug: "mobile-accessories" },
      ] },
      { id: 302, name: "Computers & Laptops", slug: "computers-laptops", detailedCategories: [
        { id: 3007, name: "Laptops", slug: "laptops" },
        { id: 3008, name: "Desktop Computers", slug: "desktop-computers" },
        { id: 3009, name: "All-in-One PCs", slug: "all-in-one-pcs" },
        { id: 3010, name: "Monitors", slug: "monitors" },
        { id: 3011, name: "Computer Accessories", slug: "computer-accessories" },
        { id: 3012, name: "Printers & Scanners", slug: "printers-scanners-computers" },
      ] },
      { id: 303, name: "TVs & Home Entertainment", slug: "tvs-home-entertainment", detailedCategories: [
        { id: 3013, name: "Smart TVs", slug: "smart-tvs" },
        { id: 3014, name: "LED TVs", slug: "led-tvs" },
        { id: 3015, name: "OLED TVs", slug: "oled-tvs" },
        { id: 3016, name: "Projectors", slug: "projectors-home-entertainment" },
        { id: 3017, name: "Streaming Devices", slug: "streaming-devices" },
        { id: 3018, name: "Home Theater Systems", slug: "home-theater-systems" },
      ] },
      { id: 304, name: "Cameras & Photography", slug: "cameras-photography", detailedCategories: [
        { id: 3019, name: "DSLR Cameras", slug: "dslr-cameras" },
        { id: 3020, name: "Mirrorless Cameras", slug: "mirrorless-cameras" },
        { id: 3021, name: "Action Cameras", slug: "action-cameras" },
        { id: 3022, name: "Camcorders", slug: "camcorders" },
        { id: 3023, name: "Camera Lenses", slug: "camera-lenses" },
        { id: 3024, name: "Photography Accessories", slug: "photography-accessories" },
      ] },
      { id: 305, name: "Audio & Music Systems", slug: "audio-music-systems", detailedCategories: [
        { id: 3025, name: "Headphones", slug: "headphones" },
        { id: 3026, name: "Earbuds", slug: "earbuds" },
        { id: 3027, name: "Bluetooth Speakers", slug: "bluetooth-speakers" },
        { id: 3028, name: "Soundbars", slug: "soundbars" },
        { id: 3029, name: "Home Audio Systems", slug: "home-audio-systems" },
        { id: 3030, name: "DJ Equipment", slug: "dj-equipment" },
      ] },
      { id: 306, name: "Gaming & Consoles", slug: "gaming-consoles", detailedCategories: [
        { id: 3031, name: "PlayStation Consoles", slug: "playstation-consoles" },
        { id: 3032, name: "Xbox Consoles", slug: "xbox-consoles" },
        { id: 3033, name: "Nintendo Consoles", slug: "nintendo-consoles" },
        { id: 3034, name: "Gaming PCs", slug: "gaming-pcs" },
        { id: 3035, name: "Gaming Accessories", slug: "gaming-accessories" },
        { id: 3036, name: "VR Headsets", slug: "vr-headsets" },
      ] },
      { id: 307, name: "Smart Home Devices", slug: "smart-home-devices", detailedCategories: [
        { id: 3037, name: "Smart Speakers", slug: "smart-speakers" },
        { id: 3038, name: "Smart Lights", slug: "smart-lights" },
        { id: 3039, name: "Smart Thermostats", slug: "smart-thermostats" },
        { id: 3040, name: "Smart Security Cameras", slug: "smart-security-cameras" },
        { id: 3041, name: "Video Doorbells", slug: "video-doorbells" },
        { id: 3042, name: "Home Automation Devices", slug: "home-automation-devices" },
      ] },
      { id: 308, name: "Home Appliances", slug: "home-appliances", detailedCategories: [
        { id: 3043, name: "Refrigerators", slug: "refrigerators" },
        { id: 3044, name: "Washing Machines", slug: "washing-machines" },
        { id: 3045, name: "Dryers", slug: "dryers" },
        { id: 3046, name: "Air Conditioners", slug: "air-conditioners" },
        { id: 3047, name: "Air Purifiers", slug: "air-purifiers" },
        { id: 3048, name: "Vacuum Cleaners", slug: "vacuum-cleaners" },
      ] },
      { id: 309, name: "Kitchen Appliances", slug: "kitchen-appliances", detailedCategories: [
        { id: 3049, name: "Microwaves", slug: "microwaves" },
        { id: 3050, name: "Ovens", slug: "ovens" },
        { id: 3051, name: "Dishwashers", slug: "dishwashers" },
        { id: 3052, name: "Coffee Makers", slug: "coffee-makers" },
        { id: 3053, name: "Mixers & Blenders", slug: "mixers-blenders" },
        { id: 3054, name: "Water Purifiers", slug: "water-purifiers" },
      ] },
      { id: 310, name: "Office Electronics", slug: "office-electronics", detailedCategories: [
        { id: 3055, name: "Printers", slug: "printers" },
        { id: 3056, name: "Scanners", slug: "scanners" },
        { id: 3057, name: "Projectors", slug: "projectors-office" },
        { id: 3058, name: "Conference Equipment", slug: "conference-equipment" },
        { id: 3059, name: "POS Systems", slug: "pos-systems" },
      ] },
      { id: 311, name: "Wearables & Accessories", slug: "wearables-accessories", detailedCategories: [
        { id: 3060, name: "Smart Watches", slug: "wearable-smart-watches" },
        { id: 3061, name: "Fitness Bands", slug: "fitness-bands" },
        { id: 3062, name: "Chargers", slug: "chargers" },
        { id: 3063, name: "Power Banks", slug: "power-banks" },
        { id: 3064, name: "Phone Cases", slug: "phone-cases" },
        { id: 3065, name: "Screen Protectors", slug: "screen-protectors" },
      ] },
      { id: 312, name: "Networking Equipment", slug: "networking-equipment", detailedCategories: [
        { id: 3066, name: "Routers", slug: "routers" },
        { id: 3067, name: "Modems", slug: "modems" },
        { id: 3068, name: "WiFi Extenders", slug: "wifi-extenders" },
        { id: 3069, name: "Network Switches", slug: "network-switches" },
        { id: 3070, name: "Access Points", slug: "access-points" },
      ] },
    ],
  },
  {
    id: 12,
    name: "Care Services",
    slug: "care-services",
    subCategories: [
      { id: 1201, name: "Child Care Services", slug: "child-care-services", detailedCategories: [
        { id: 12001, name: "Day Care Centers", slug: "day-care-centers" },
        { id: 12002, name: "After School Care", slug: "after-school-care" },
        { id: 12003, name: "Infant Care", slug: "infant-care" },
        { id: 12004, name: "Preschool Care", slug: "preschool-care" },
        { id: 12005, name: "Weekend Child Care", slug: "weekend-child-care" },
        { id: 12006, name: "Emergency Child Care", slug: "emergency-child-care" },
      ] },
      { id: 1202, name: "Elder Care Services", slug: "elder-care-services", detailedCategories: [
        { id: 12007, name: "Senior Companion Care", slug: "senior-companion-care" },
        { id: 12008, name: "Assisted Living Support", slug: "assisted-living-support" },
        { id: 12009, name: "Dementia & Alzheimer's Care", slug: "dementia-alzheimers-care" },
        { id: 12010, name: "Live-in Elder Care", slug: "live-in-elder-care" },
        { id: 12011, name: "Respite Care", slug: "respite-care" },
        { id: 12012, name: "Mobility Assistance", slug: "mobility-assistance" },
      ] },
      { id: 1203, name: "Home Health Care", slug: "home-health-care", detailedCategories: [
        { id: 12013, name: "Home Care Aides", slug: "home-care-aides" },
        { id: 12014, name: "Post-Surgery Care", slug: "post-surgery-care" },
        { id: 12015, name: "Medication Assistance", slug: "medication-assistance" },
        { id: 12016, name: "In-home Monitoring", slug: "in-home-monitoring" },
        { id: 12017, name: "Personal Hygiene Assistance", slug: "personal-hygiene-assistance" },
      ] },
      { id: 1204, name: "Nursing Services", slug: "nursing-services", detailedCategories: [
        { id: 12018, name: "Registered Nurses (RN)", slug: "registered-nurses-rn" },
        { id: 12019, name: "Licensed Practical Nurses (LPN)", slug: "licensed-practical-nurses-lpn" },
        { id: 12020, name: "CNA Services", slug: "cna-services" },
        { id: 12021, name: "Injection & IV Services", slug: "injection-iv-services" },
        { id: 12022, name: "Wound Care Services", slug: "wound-care-services" },
      ] },
      { id: 1205, name: "Disability & Special Needs Care", slug: "disability-special-needs-care", detailedCategories: [
        { id: 12023, name: "Autism Support Care", slug: "autism-support-care" },
        { id: 12024, name: "Special Needs Babysitting", slug: "special-needs-babysitting" },
        { id: 12025, name: "Physical Disability Assistance", slug: "physical-disability-assistance" },
        { id: 12026, name: "Behavioral Therapy Support", slug: "behavioral-therapy-support" },
      ] },
      { id: 1206, name: "Pet Care Services", slug: "pet-care-services", detailedCategories: [
        { id: 12027, name: "Pet Sitting", slug: "pet-sitting" },
        { id: 12028, name: "Dog Walking", slug: "dog-walking" },
        { id: 12029, name: "Pet Boarding", slug: "pet-boarding" },
        { id: 12030, name: "Grooming Services", slug: "grooming-services" },
        { id: 12031, name: "Overnight Pet Care", slug: "overnight-pet-care" },
      ] },
      { id: 1207, name: "Babysitting & Nanny Services", slug: "babysitting-nanny-services", detailedCategories: [
        { id: 12032, name: "Full-time Nanny", slug: "full-time-nanny" },
        { id: 12033, name: "Part-time Babysitter", slug: "part-time-babysitter" },
        { id: 12034, name: "Live-in Nanny", slug: "live-in-nanny" },
        { id: 12035, name: "Night Nanny", slug: "night-nanny" },
        { id: 12036, name: "Vacation Babysitting", slug: "vacation-babysitting" },
      ] },
      { id: 1208, name: "Companion Care Services", slug: "companion-care-services", detailedCategories: [
        { id: 12037, name: "Companionship Visits", slug: "companionship-visits" },
        { id: 12038, name: "Transportation Assistance", slug: "transportation-assistance" },
        { id: 12039, name: "Grocery & Errand Help", slug: "grocery-errand-help" },
        { id: 12040, name: "Social Activity Assistance", slug: "social-activity-assistance" },
      ] },
      { id: 1209, name: "Rehabilitation & Therapy Services", slug: "rehabilitation-therapy-services", detailedCategories: [
        { id: 12041, name: "Physical Therapy", slug: "physical-therapy" },
        { id: 12042, name: "Occupational Therapy", slug: "occupational-therapy" },
        { id: 12043, name: "Speech Therapy", slug: "speech-therapy" },
        { id: 12044, name: "Behavioral Therapy", slug: "behavioral-therapy" },
      ] },
      { id: 1210, name: "Hospice & Palliative Care", slug: "hospice-palliative-care", detailedCategories: [
        { id: 12045, name: "End-of-Life Care", slug: "end-of-life-care" },
        { id: 12046, name: "Pain Management Support", slug: "pain-management-support" },
        { id: 12047, name: "Emotional & Family Support", slug: "emotional-family-support" },
      ] },
    ],
  },
  {
    id: 4,
    name: "Furniture & Home",
    slug: "furniture-home-decor",
    subCategories: [
      { id: 401, name: "Living Room Furniture", slug: "living-room-furniture", detailedCategories: [
        { id: 4001, name: "Sofas", slug: "sofas" },
        { id: 4002, name: "Sectional Sofas", slug: "sectional-sofas" },
        { id: 4003, name: "Recliners", slug: "recliners" },
        { id: 4004, name: "Coffee Tables", slug: "coffee-tables" },
        { id: 4005, name: "TV Stands", slug: "tv-stands" },
        { id: 4006, name: "Entertainment Centers", slug: "entertainment-centers" },
        { id: 4007, name: "Accent Chairs", slug: "accent-chairs" },
      ] },
      { id: 402, name: "Bedroom Furniture", slug: "bedroom-furniture", detailedCategories: [
        { id: 4008, name: "Beds", slug: "beds" },
        { id: 4009, name: "Bedroom Sets", slug: "bedroom-sets" },
        { id: 4010, name: "Dressers", slug: "dressers" },
        { id: 4011, name: "Wardrobes", slug: "wardrobes" },
        { id: 4012, name: "Nightstands", slug: "nightstands" },
        { id: 4013, name: "Bunk Beds", slug: "bunk-beds" },
        { id: 4014, name: "Kids Bedroom Furniture", slug: "kids-bedroom-furniture" },
      ] },
      { id: 403, name: "Dining Room Furniture", slug: "dining-room-furniture", detailedCategories: [
        { id: 4015, name: "Dining Tables", slug: "dining-tables" },
        { id: 4016, name: "Dining Chairs", slug: "dining-chairs" },
        { id: 4017, name: "Dining Sets", slug: "dining-sets" },
        { id: 4018, name: "Bar Stools", slug: "bar-stools" },
        { id: 4019, name: "Buffets & Sideboards", slug: "buffets-sideboards" },
      ] },
      { id: 404, name: "Office Furniture", slug: "office-furniture", detailedCategories: [
        { id: 4020, name: "Office Desks", slug: "office-desks" },
        { id: 4021, name: "Computer Tables", slug: "computer-tables" },
        { id: 4022, name: "Office Chairs", slug: "office-chairs" },
        { id: 4023, name: "Standing Desks", slug: "standing-desks" },
        { id: 4024, name: "Conference Tables", slug: "conference-tables" },
        { id: 4025, name: "Filing Cabinets", slug: "filing-cabinets" },
      ] },
      { id: 405, name: "Outdoor & Patio Furniture", slug: "outdoor-patio-furniture", detailedCategories: [
        { id: 4026, name: "Patio Sets", slug: "patio-sets" },
        { id: 4027, name: "Garden Furniture", slug: "garden-furniture" },
        { id: 4028, name: "Outdoor Chairs", slug: "outdoor-chairs" },
        { id: 4029, name: "Outdoor Dining Sets", slug: "outdoor-dining-sets" },
        { id: 4030, name: "Umbrellas", slug: "umbrellas" },
        { id: 4031, name: "Fire Pit Furniture", slug: "fire-pit-furniture" },
      ] },
      { id: 406, name: "Home Decor", slug: "home-decor", detailedCategories: [
        { id: 4032, name: "Wall Art", slug: "wall-art" },
        { id: 4033, name: "Mirrors", slug: "mirrors" },
        { id: 4034, name: "Rugs & Carpets", slug: "rugs-carpets" },
        { id: 4035, name: "Curtains", slug: "curtains" },
        { id: 4036, name: "Decorative Items", slug: "decorative-items" },
        { id: 4037, name: "Clocks", slug: "clocks" },
      ] },
      { id: 407, name: "Lighting & Fixtures", slug: "lighting-fixtures", detailedCategories: [
        { id: 4038, name: "Chandeliers", slug: "chandeliers" },
        { id: 4039, name: "Ceiling Lights", slug: "ceiling-lights" },
        { id: 4040, name: "Floor Lamps", slug: "floor-lamps" },
        { id: 4041, name: "Table Lamps", slug: "table-lamps" },
        { id: 4042, name: "Outdoor Lighting", slug: "outdoor-lighting" },
      ] },
      { id: 408, name: "Storage & Organization", slug: "storage-organization", detailedCategories: [
        { id: 4043, name: "Bookshelves", slug: "bookshelves" },
        { id: 4044, name: "Storage Cabinets", slug: "storage-cabinets" },
        { id: 4045, name: "Shoe Racks", slug: "shoe-racks" },
        { id: 4046, name: "Closet Organizers", slug: "closet-organizers" },
        { id: 4047, name: "Shelving Units", slug: "shelving-units" },
      ] },
      { id: 409, name: "Mattresses & Bedding", slug: "mattresses-bedding", detailedCategories: [
        { id: 4048, name: "Mattresses", slug: "mattresses" },
        { id: 4049, name: "Bed Frames", slug: "bed-frames" },
        { id: 4050, name: "Pillows", slug: "pillows" },
        { id: 4051, name: "Bedding Sets", slug: "bedding-sets" },
        { id: 4052, name: "Mattress Toppers", slug: "mattress-toppers" },
      ] },
      { id: 410, name: "Kitchen & Dining Essentials", slug: "kitchen-dining-essentials", detailedCategories: [
        { id: 4053, name: "Cookware", slug: "cookware" },
        { id: 4054, name: "Dinnerware", slug: "dinnerware" },
        { id: 4055, name: "Kitchen Storage", slug: "kitchen-storage" },
        { id: 4056, name: "Small Kitchen Furniture", slug: "small-kitchen-furniture" },
      ] },
      { id: 411, name: "Home Improvement Materials", slug: "home-improvement-materials", detailedCategories: [
        { id: 4057, name: "Doors", slug: "doors" },
        { id: 4058, name: "Windows", slug: "windows" },
        { id: 4059, name: "Flooring", slug: "flooring" },
        { id: 4060, name: "Cabinets", slug: "cabinets" },
        { id: 4061, name: "Countertops", slug: "countertops" },
      ] },
      { id: 412, name: "Antique & Vintage Furniture", slug: "antique-vintage-furniture", detailedCategories: [
        { id: 4062, name: "Antique Tables", slug: "antique-tables" },
        { id: 4063, name: "Vintage Chairs", slug: "vintage-chairs" },
        { id: 4064, name: "Collectible Furniture", slug: "collectible-furniture" },
        { id: 4065, name: "Restoration Pieces", slug: "restoration-pieces" },
      ] },
    ],
  },
  {
    id: 5,
    name: "Fashion & Lifestyle",
    slug: "fashion-lifestyle",
    subCategories: [
      { id: 501, name: "Men", slug: "men", detailedCategories: [
        { id: 5001, name: "Clothing", slug: "mens-clothing" },
        { id: 5002, name: "Footwear", slug: "mens-footwear" },
      ] },
      { id: 502, name: "Women", slug: "women", detailedCategories: [
        { id: 5003, name: "Clothing", slug: "womens-clothing" },
        { id: 5004, name: "Footwear", slug: "womens-footwear" },
      ] },
      { id: 503, name: "Kids", slug: "kids", detailedCategories: [
        { id: 5005, name: "Clothing", slug: "kids-clothing" },
        { id: 5006, name: "Footwear", slug: "kids-footwear" },
      ] },
      { id: 504, name: "Accessories", slug: "fashion-accessories", detailedCategories: [
        { id: 5007, name: "Watches", slug: "watches" },
        { id: 5008, name: "Jewelry", slug: "jewelry" },
        { id: 5009, name: "Handbags", slug: "handbags" },
        { id: 5010, name: "Sunglasses", slug: "sunglasses" },
      ] },
    ],
  },
  {
    id: 6,
    name: "Pets & Animals",
    slug: "pets-animals",
    subCategories: [
      { id: 601, name: "Dogs", slug: "dogs", detailedCategories: [
        { id: 6001, name: "Puppies for Adoption", slug: "puppies-for-adoption" },
        { id: 6002, name: "Adult Dogs", slug: "adult-dogs" },
        { id: 6003, name: "Purebred Dogs", slug: "purebred-dogs" },
        { id: 6004, name: "Mixed Breed Dogs", slug: "mixed-breed-dogs" },
        { id: 6005, name: "Dog Breeding Services", slug: "dog-breeding-services" },
      ] },
      { id: 602, name: "Cats", slug: "cats", detailedCategories: [
        { id: 6006, name: "Kittens for Adoption", slug: "kittens-for-adoption" },
        { id: 6007, name: "Adult Cats", slug: "adult-cats" },
        { id: 6008, name: "Purebred Cats", slug: "purebred-cats" },
        { id: 6009, name: "Mixed Breed Cats", slug: "mixed-breed-cats" },
      ] },
      { id: 603, name: "Birds", slug: "birds", detailedCategories: [
        { id: 6010, name: "Parrots", slug: "parrots" },
        { id: 6011, name: "Cockatiels", slug: "cockatiels" },
        { id: 6012, name: "Love Birds", slug: "love-birds" },
        { id: 6013, name: "Canaries", slug: "canaries" },
        { id: 6014, name: "Exotic Birds", slug: "exotic-birds" },
      ] },
      { id: 604, name: "Fish & Aquariums", slug: "fish-aquariums", detailedCategories: [
        { id: 6015, name: "Freshwater Fish", slug: "freshwater-fish" },
        { id: 6016, name: "Saltwater Fish", slug: "saltwater-fish" },
        { id: 6017, name: "Aquarium Setup", slug: "aquarium-setup" },
        { id: 6018, name: "Aquarium Accessories", slug: "aquarium-accessories" },
      ] },
      { id: 605, name: "Small Pets", slug: "small-pets", detailedCategories: [
        { id: 6019, name: "Rabbits", slug: "rabbits" },
        { id: 6020, name: "Guinea Pigs", slug: "guinea-pigs" },
        { id: 6021, name: "Hamsters", slug: "hamsters" },
        { id: 6022, name: "Ferrets", slug: "ferrets" },
        { id: 6023, name: "Hedgehogs", slug: "hedgehogs" },
      ] },
      { id: 606, name: "Reptiles & Amphibians", slug: "reptiles-amphibians", detailedCategories: [
        { id: 6024, name: "Turtles", slug: "turtles" },
        { id: 6025, name: "Lizards", slug: "lizards" },
        { id: 6026, name: "Geckos", slug: "geckos" },
        { id: 6027, name: "Snakes", slug: "snakes" },
        { id: 6028, name: "Frogs", slug: "frogs" },
      ] },
      { id: 607, name: "Horses & Livestock", slug: "horses-livestock", detailedCategories: [
        { id: 6029, name: "Horses", slug: "horses" },
        { id: 6030, name: "Ponies", slug: "ponies" },
        { id: 6031, name: "Goats", slug: "goats" },
        { id: 6032, name: "Sheep", slug: "sheep" },
        { id: 6033, name: "Farm Animals", slug: "farm-animals" },
      ] },
      { id: 608, name: "Pet Adoption", slug: "pet-adoption", detailedCategories: [
        { id: 6034, name: "Dog Adoption", slug: "dog-adoption" },
        { id: 6035, name: "Cat Adoption", slug: "cat-adoption" },
        { id: 6036, name: "Bird Adoption", slug: "bird-adoption" },
        { id: 6037, name: "Rescue Organizations", slug: "rescue-organizations" },
      ] },
      { id: 609, name: "Pet Services", slug: "pet-services", detailedCategories: [
        { id: 6038, name: "Pet Grooming", slug: "pet-grooming" },
        { id: 6039, name: "Pet Training", slug: "pet-training" },
        { id: 6040, name: "Veterinary Services", slug: "veterinary-services" },
        { id: 6041, name: "Pet Walking", slug: "pet-walking" },
        { id: 6042, name: "Pet Sitting", slug: "pets-pet-sitting" },
      ] },
      { id: 610, name: "Pet Supplies & Accessories", slug: "pet-supplies-accessories", detailedCategories: [
        { id: 6043, name: "Pet Food", slug: "pet-food" },
        { id: 6044, name: "Pet Toys", slug: "pet-toys" },
        { id: 6045, name: "Pet Beds", slug: "pet-beds" },
        { id: 6046, name: "Leashes & Collars", slug: "leashes-collars" },
        { id: 6047, name: "Pet Cages", slug: "pet-cages" },
      ] },
      { id: 611, name: "Pet Boarding & Daycare", slug: "pet-boarding-daycare", detailedCategories: [
        { id: 6048, name: "Overnight Boarding", slug: "overnight-boarding" },
        { id: 6049, name: "Pet Daycare", slug: "pet-daycare" },
        { id: 6050, name: "Luxury Pet Hotels", slug: "luxury-pet-hotels" },
        { id: 6051, name: "Long-Term Boarding", slug: "long-term-boarding" },
      ] },
      { id: 612, name: "Lost & Found Pets", slug: "lost-found-pets", detailedCategories: [
        { id: 6052, name: "Lost Dogs", slug: "lost-dogs" },
        { id: 6053, name: "Lost Cats", slug: "lost-cats" },
        { id: 6054, name: "Found Pets", slug: "found-pets" },
        { id: 6055, name: "Pet Recovery Services", slug: "pet-recovery-services" },
      ] },
    ],
  },
  {
    id: 7,
    name: "Books, Sports & Hobbies",
    slug: "books-sports-hobbies",
    subCategories: [
      { id: 701, name: "Books", slug: "books", detailedCategories: [
        { id: 7001, name: "Academic Books", slug: "academic-books" },
      ] },
      { id: 702, name: "Sports Equipment", slug: "sports-equipment", detailedCategories: [
        { id: 7002, name: "Gym Equipment", slug: "gym-equipment" },
        { id: 7003, name: "Cricket / Football Gear", slug: "cricket-football-gear" },
      ] },
      { id: 703, name: "Musical Instruments", slug: "musical-instruments", detailedCategories: [
        { id: 7004, name: "Guitars / Keyboards", slug: "guitars-keyboards" },
      ] },
      { id: 704, name: "Hobby Items", slug: "hobby-items", detailedCategories: [
        { id: 7005, name: "Collectibles", slug: "collectibles" },
      ] },
    ],
  },
  {
    id: 8,
    name: "Jobs / Services",
    slug: "jobs-services",
    subCategories: [
      { id: 801, name: "Job Listings", slug: "job-listings", detailedCategories: [
        { id: 8001, name: "IT Jobs", slug: "it-jobs" },
        { id: 8002, name: "Part-time Jobs", slug: "part-time-jobs" },
      ] },
      { id: 802, name: "Freelance Services", slug: "freelance-services", detailedCategories: [
        { id: 8003, name: "Home Services", slug: "home-services" },
        { id: 8004, name: "Tuition / Training", slug: "tuition-training" },
      ] },
    ],
  },
  {
    id: 9,
    name: "Business & Industrial",
    slug: "business-industrial",
    subCategories: [
      { id: 901, name: "Machinery", slug: "machinery", detailedCategories: [
        { id: 9001, name: "Manufacturing Equipment", slug: "manufacturing-equipment" },
      ] },
      { id: 902, name: "Industrial Supplies", slug: "industrial-supplies", detailedCategories: [
        { id: 9002, name: "Construction Tools", slug: "construction-tools" },
      ] },
      { id: 903, name: "Bulk Products", slug: "bulk-products", detailedCategories: [
        { id: 9003, name: "Raw Materials", slug: "raw-materials" },
        { id: 9004, name: "Packaging Materials", slug: "packaging-materials" },
      ] },
    ],
  },
  {
    id: 10,
    name: "Events & Tickets",
    slug: "events-tickets",
    subCategories: [
      { id: 1001, name: "Concerts & Music Events", slug: "concerts-music-events", detailedCategories: [
        { id: 10001, name: "Live Concerts", slug: "live-concerts" },
        { id: 10002, name: "DJ Nights", slug: "dj-nights" },
        { id: 10003, name: "Karaoke Events", slug: "karaoke-events" },
        { id: 10004, name: "Band Performances", slug: "band-performances" },
        { id: 10005, name: "Classical Music Events", slug: "classical-music-events" },
        { id: 10006, name: "Music Tours", slug: "music-tours" },
      ] },
      { id: 1002, name: "Festivals & Cultural Events", slug: "festivals-cultural-events", detailedCategories: [
        { id: 10007, name: "Food Festivals", slug: "food-festivals" },
        { id: 10008, name: "Cultural Festivals", slug: "cultural-festivals" },
        { id: 10009, name: "Seasonal Festivals", slug: "seasonal-festivals" },
        { id: 10010, name: "Art Festivals", slug: "art-festivals" },
        { id: 10011, name: "Film Festivals", slug: "film-festivals" },
        { id: 10012, name: "Community Celebrations", slug: "community-celebrations" },
      ] },
      { id: 1003, name: "Sports Events", slug: "sports-events", detailedCategories: [
        { id: 10013, name: "Football Games", slug: "football-games" },
        { id: 10014, name: "Basketball Games", slug: "basketball-games" },
        { id: 10015, name: "Cricket Matches", slug: "cricket-matches" },
        { id: 10016, name: "Baseball Games", slug: "baseball-games" },
        { id: 10017, name: "Marathon / Running Events", slug: "marathon-running-events" },
        { id: 10018, name: "Fitness Competitions", slug: "fitness-competitions" },
      ] },
      { id: 1004, name: "Business & Networking Events", slug: "business-networking-events", detailedCategories: [
        { id: 10019, name: "Networking Meetups", slug: "networking-meetups" },
        { id: 10020, name: "Startup Events", slug: "startup-events" },
        { id: 10021, name: "Trade Shows", slug: "trade-shows" },
        { id: 10022, name: "Conferences", slug: "conferences" },
        { id: 10023, name: "Career Fairs", slug: "career-fairs" },
        { id: 10024, name: "Business Seminars", slug: "business-seminars" },
      ] },
      { id: 1005, name: "Workshops & Classes", slug: "workshops-classes", detailedCategories: [
        { id: 10025, name: "Cooking Classes", slug: "cooking-classes" },
        { id: 10026, name: "Dance Workshops", slug: "dance-workshops" },
        { id: 10027, name: "Tech Workshops", slug: "tech-workshops" },
        { id: 10028, name: "Photography Classes", slug: "photography-classes" },
        { id: 10029, name: "Language Classes", slug: "language-classes" },
        { id: 10030, name: "Fitness Classes", slug: "fitness-classes" },
      ] },
      { id: 1006, name: "Community Events", slug: "community-events", detailedCategories: [
        { id: 10031, name: "Local Meetups", slug: "local-meetups" },
        { id: 10032, name: "Volunteer Events", slug: "volunteer-events" },
        { id: 10033, name: "Charity Events", slug: "charity-events" },
        { id: 10034, name: "Awareness Programs", slug: "awareness-programs" },
        { id: 10035, name: "Neighborhood Gatherings", slug: "neighborhood-gatherings" },
      ] },
      { id: 1007, name: "Parties & Nightlife", slug: "parties-nightlife", detailedCategories: [
        { id: 10036, name: "Birthday Parties", slug: "birthday-parties" },
        { id: 10037, name: "Club Events", slug: "club-events" },
        { id: 10038, name: "Pool Parties", slug: "pool-parties" },
        { id: 10039, name: "Bachelor / Bachelorette Parties", slug: "bachelor-bachelorette-parties" },
        { id: 10040, name: "Lounge Events", slug: "lounge-events" },
      ] },
      { id: 1008, name: "Religious & Spiritual Events", slug: "religious-spiritual-events", detailedCategories: [
        { id: 10041, name: "Temple Events", slug: "temple-events" },
        { id: 10042, name: "Church Gatherings", slug: "church-gatherings" },
        { id: 10043, name: "Meditation Sessions", slug: "meditation-sessions" },
        { id: 10044, name: "Spiritual Retreats", slug: "spiritual-retreats" },
        { id: 10045, name: "Religious Festivals", slug: "religious-festivals" },
      ] },
      { id: 1009, name: "Kids & Family Events", slug: "kids-family-events", detailedCategories: [
        { id: 10046, name: "Kids Camps", slug: "kids-camps" },
        { id: 10047, name: "Family Fun Events", slug: "family-fun-events" },
        { id: 10048, name: "Puppet Shows", slug: "puppet-shows" },
        { id: 10049, name: "School Events", slug: "school-events" },
        { id: 10050, name: "Science Exhibitions", slug: "science-exhibitions" },
      ] },
      { id: 1010, name: "Virtual / Online Events", slug: "virtual-online-events", detailedCategories: [
        { id: 10051, name: "Webinars", slug: "webinars" },
        { id: 10052, name: "Online Classes", slug: "online-classes" },
        { id: 10053, name: "Virtual Networking", slug: "virtual-networking" },
        { id: 10054, name: "Live Streaming Events", slug: "live-streaming-events" },
      ] },
      { id: 1011, name: "Ticket Resale & Exchange", slug: "ticket-resale-exchange", detailedCategories: [
        { id: 10055, name: "Concert Ticket Resale", slug: "concert-ticket-resale" },
        { id: 10056, name: "Sports Ticket Exchange", slug: "sports-ticket-exchange" },
        { id: 10057, name: "Event Pass Transfers", slug: "event-pass-transfers" },
        { id: 10058, name: "VIP Ticket Sales", slug: "vip-ticket-sales" },
      ] },
    ],
  },
].filter((category) => supportedListingCategoryNameSet.has(category.name));
