import { useState, type FormEvent, type ReactNode } from "react";
import { communityApi } from "../api/communityApi";

export default function CommunityGiftDashboard({items,done}:{items:Record<string,unknown>[];done:()=>Promise<void>}){
 const [showCreate,setShowCreate]=useState(false),[selected,setSelected]=useState<Record<string,unknown>>(),[detail,setDetail]=useState<Record<string,unknown>>(),[showItem,setShowItem]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function open(item:Record<string,unknown>){setSelected(item);setError("");try{setDetail(await communityApi.giftRegistry(Number(item.id)))}catch(e){setError(e instanceof Error?e.message:"Unable to open registry.")}}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);try{await communityApi.createRegistry({title:form.get("title"),description:form.get("description"),visibility:form.get("visibility")});setShowCreate(false);await done()}finally{setBusy(false)}}
 async function addItem(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);setBusy(true);try{await communityApi.addGiftRegistryItem(Number(selected.id),{name:form.get("name"),description:form.get("description"),imageUrl:form.get("imageUrl")||undefined,externalUrl:form.get("externalUrl")||undefined,desiredAmount:Number(form.get("desiredAmount"))||undefined,desiredQuantity:Number(form.get("desiredQuantity"))||1});setDetail(await communityApi.giftRegistry(Number(selected.id)));setShowItem(false);await done()}finally{setBusy(false)}}
 const giftItems=Array.isArray(detail?.items)?detail.items as Record<string,unknown>[]:[];
 return <><div className="community-list-head gift-dashboard-head"><div><h2>Gift registries</h2><p>Create wish lists and manage gift ideas in one place.</p></div><button className="community-create-button" onClick={()=>setShowCreate(true)}><span className="material-icons">card_giftcard</span>New registry</button></div>{error?<p className="community-error">{error}</p>:null}<div className="gift-registry-grid">{items.map((item,index)=><article key={String(item.id??index)}><div className="gift-registry-art"><span className="material-icons">redeem</span><small>{String(item.visibility||"PRIVATE")}</small></div><div><h3>{String(item.title||"Gift registry")}</h3><p>{String(item.description||"A curated collection of meaningful gift ideas.")}</p><span>{Number(item.itemCount||0)} gift ideas</span><button className="gift-open" onClick={()=>void open(item)}>Manage registry</button></div></article>)}</div>{selected&&detail?<section className="gift-detail"><header><div><small>REGISTRY ITEMS</small><h2>{String(detail.title||selected.title)}</h2></div><button onClick={()=>setShowItem(true)}><span className="material-icons">add</span>Add gift idea</button></header><div className="gift-item-grid">{giftItems.map(item=><article key={String(item.id)}>{item.imageUrl?<img src={String(item.imageUrl)} alt=""/>:<span className="material-icons">featured_seasonal_and_gifts</span>}<div><h3>{String(item.name)}</h3><p>{String(item.description||"")}</p><strong>{Number(item.desiredAmount||0)>0?Number(item.desiredAmount).toLocaleString(undefined,{style:"currency",currency:String(item.currency||"USD")}):"Any amount"}</strong><small>{Number(item.purchasedQuantity||0)} of {Number(item.desiredQuantity||1)} received</small>{item.externalUrl?<a href={String(item.externalUrl)} target="_blank" rel="noreferrer">View item</a>:null}</div></article>)}</div></section>:null}{showCreate?<Modal title="Create a gift registry" icon="card_giftcard" close={()=>setShowCreate(false)}><form className="gift-form" onSubmit={create}><label>Registry title<input name="title" required/></label><label>Visibility<select name="visibility"><option>PRIVATE</option><option>INVITEES</option><option>PUBLIC</option></select></label><label>Description<textarea name="description"/></label><button disabled={busy}>Create registry</button></form></Modal>:null}{showItem?<Modal title="Add a gift idea" icon="redeem" close={()=>setShowItem(false)}><form className="gift-form" onSubmit={addItem}><label>Gift name<input name="name" required/></label><label>Description<textarea name="description"/></label><label>Image URL<input name="imageUrl" type="url"/></label><label>Store URL<input name="externalUrl" type="url"/></label><div><label>Estimated price<input name="desiredAmount" type="number" min="0" step="0.01"/></label><label>Quantity<input name="desiredQuantity" type="number" min="1" defaultValue="1"/></label></div><button disabled={busy}>Add gift idea</button></form></Modal>:null}</>;
}
function Modal({title,icon,close,children}:{title:string;icon:string;close:()=>void;children:ReactNode}){return <div className="community-modal" role="dialog" aria-modal="true" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div className="community-modal-card"><header><div><span className="material-icons">{icon}</span><div><small>COMMUNITY GIFTS</small><h2>{title}</h2></div></div><button onClick={close}>×</button></header>{children}</div></div>}
