import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { HubConnectionBuilder, LogLevel } from "@microsoft/signalr";
import UserHomeHeader from "../../home/ui/UserHomeHeader";
import HomeFooterSection from "../../home/ui/HomeFooterSection";
import { communityApi, discoverCommunityWithFallback, enterCommunity, type CommunityConversation, type CommunityEvent, type CommunityGroup, type CommunityGroupMember, type CommunityMessage, type CommunityPost } from "../api/communityApi";
import { getCustomerToken } from "../../auth/utils/customerSession";
import { env } from "../../../app/config/env";
import { useHomeSelectedLocation } from "../../home/hooks/useHomeSelectedLocation";
import "./communityPortal.css";

const nav = [["discover","Discover"],["groups","My Groups"],["feed","Feed"],["messages","Messages"],["events","Events"],["invitations","Invitations"],["gifts","Gifts"],["notifications","Notifications"],["profile","Profile"]];
export default function CommunityPortalPage() {
  const { section = "discover" } = useParams();
  return <><UserHomeHeader hideAddAction /><main className="community-portal"><header><div><span>ChaoDesi Groups &amp; Communities</span><h1>{nav.find(x=>x[0]===section)?.[1] || "Groups & Communities"}</h1></div><Link to="/community">Groups &amp; Communities home</Link></header><nav>{nav.map(([key,label])=><Link className={section===key?"active":""} key={key} to={`/community/${key}`}>{label}</Link>)}</nav><CommunitySection section={section}/></main><HomeFooterSection /></>;
}

function CommunitySection({section}:{section:string}) {
  const { activeCity } = useHomeSelectedLocation();
  const [groups,setGroups]=useState<CommunityGroup[]>([]), [posts,setPosts]=useState<CommunityPost[]>([]), [events,setEvents]=useState<CommunityEvent[]>([]);
  const [conversations,setConversations]=useState<CommunityConversation[]>([]), [messages,setMessages]=useState<CommunityMessage[]>([]), [selected,setSelected]=useState<number>();
  const [contacts,setContacts]=useState<CommunityGroupMember[]>([]);
  const [items,setItems]=useState<Record<string,unknown>[]>([]), [error,setError]=useState(""), [busy,setBusy]=useState(true);
  const reload=useCallback(async()=>{setBusy(true);setError("");try{
    if(section==="discover"){const x=await discoverCommunityWithFallback(activeCity || undefined);setGroups(x.groups);setEvents(x.events);}
    else if(section==="groups"||section==="feed"){const x=await communityApi.groups({pageSize:100});setGroups(x.items);if(section==="feed"&&x.items[0])setPosts((await communityApi.posts(x.items[0].id)).items);}
    else if(section==="messages"){
      const [conversationPage,groupPage,me]=await Promise.all([communityApi.conversations(),communityApi.groups({pageSize:100}),enterCommunity()]);setConversations(conversationPage.items);
      const memberResults=await Promise.allSettled(groupPage.items.filter(group=>group.currentUserRole).map(group=>communityApi.groupMembers(group.id)));
      const unique=new Map<number,CommunityGroupMember>();
      memberResults.forEach(result=>{if(result.status==="fulfilled")result.value.items.filter(member=>member.userId!==me.id).forEach(member=>unique.set(member.userId,member))});
      setContacts([...unique.values()].sort((a,b)=>a.displayName.localeCompare(b.displayName)));
    }
    else if(section==="events")setEvents((await communityApi.events({pageSize:100})).items);
    else if(section==="invitations")setItems((await communityApi.invitations()).items);
    else if(section==="notifications")setItems((await communityApi.notifications()).items);
  }catch(e){setError(e instanceof Error?e.message:"Unable to load Community data.");}finally{setBusy(false)}},[activeCity,section]);
  useEffect(()=>{void reload()},[reload]);
  useEffect(()=>{
    if(section!=="messages"||!selected)return;
    const apiBase=import.meta.env.VITE_API_BASE_URL||env.apiBaseUrl;
    const connection=new HubConnectionBuilder().withUrl(`${apiBase.replace(/\/api\/?$/i,"")}/hubs/community`,{accessTokenFactory:()=>getCustomerToken()||""}).withAutomaticReconnect([0,2000,5000,10000]).configureLogging(LogLevel.Warning).build();
    connection.on("message",(message:CommunityMessage)=>{if(message.conversationId===selected)setMessages(current=>current.some(x=>x.id===message.id)?current:[message,...current])});
    void connection.start().then(()=>connection.invoke("JoinConversation",selected)).catch(()=>undefined);
    return()=>{void connection.invoke("LeaveConversation",selected).catch(()=>undefined).finally(()=>connection.stop())};
  },[section,selected]);
  if(busy)return <div className="community-state">Loading…</div>;
  return <section className="community-workspace">{error&&<p className="community-error">{error}</p>}
    {section==="discover"&&<><h2>Recommended groups</h2><GroupCards groups={groups} reload={reload}/><h2>Upcoming near you</h2><EventCards events={events}/></>}
    {section==="groups"&&<GroupsView groups={groups} reload={reload}/>}
    {section==="feed"&&<><GroupPicker groups={groups} onPick={async id=>setPosts((await communityApi.posts(id)).items)}/><CreatePost groups={groups} done={reload}/><PostCards posts={posts}/></>}
    {section==="messages"&&<div className="community-messages"><aside><StartDirect contacts={contacts} done={reload}/>{conversations.map(c=><button key={c.id} onClick={async()=>{setSelected(c.id);setMessages((await communityApi.messages(c.id)).items)}}>{c.title||c.conversationType}<small>{c.unreadCount} unread</small></button>)}</aside><div>{selected?<><div className="message-list">{messages.map(m=><p key={m.id}><strong>{m.senderName}</strong>{m.body}<small>{new Date(m.sentAtUtc).toLocaleString()}</small></p>)}</div><SendMessage id={selected} done={async()=>setMessages((await communityApi.messages(selected)).items)}/></>:<div className="community-state">Select a conversation</div>}</div></div>}
    {section==="events"&&<><CreateEvent done={reload}/><EventCards events={events} register/></>}
    {section==="invitations"&&<><Link className="community-primary" to="/community/invitations/new">Build an invitation</Link><InvitationCards items={items}/></>}
    {section==="gifts"&&<CreateRegistry/>}{section==="notifications"&&<ObjectCards items={items} empty="You are all caught up."/>}
    {section==="profile"&&<Profile/>}
  </section>;
}

function GroupsView({groups,reload}:{groups:CommunityGroup[];reload:()=>Promise<void>}){const [showCreate,setShowCreate]=useState(false),[page,setPage]=useState(1);const pageSize=6,totalPages=Math.max(1,Math.ceil(groups.length/pageSize)),visible=groups.slice((page-1)*pageSize,page*pageSize);useEffect(()=>{if(page>totalPages)setPage(totalPages)},[page,totalPages]);return <><div className="community-list-head"><div><h2>Your communities</h2><p>Connect, share and participate with people near you.</p></div><button className="community-create-button" onClick={()=>setShowCreate(true)}><span className="material-icons">add</span>Create group</button></div><GroupCards groups={visible} reload={reload}/>{totalPages>1&&<nav className="community-pagination" aria-label="Group pages"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>← Previous</button><span>Page {page} of {totalPages}</span><button disabled={page===totalPages} onClick={()=>setPage(value=>value+1)}>Next →</button></nav>}{showCreate&&<div className="community-modal" role="dialog" aria-modal="true" aria-labelledby="create-group-title" onMouseDown={event=>{if(event.target===event.currentTarget)setShowCreate(false)}}><div className="community-modal-card"><header><div><span className="material-icons">groups</span><div><small>NEW COMMUNITY</small><h2 id="create-group-title">Create a group</h2></div></div><button aria-label="Close create group" onClick={()=>setShowCreate(false)}>×</button></header><p>Build a welcoming space for people in your area.</p><CreateGroup done={async()=>{await reload();setShowCreate(false)}} cancel={()=>setShowCreate(false)}/></div></div>}</>}
function GroupCards({groups,reload}:{groups:CommunityGroup[];reload:()=>Promise<void>}){return <div className="community-cards community-group-cards">{groups.map(g=><article key={g.id}><div className="community-group-cover"><span className="material-icons">groups</span><em>{g.visibility}</em></div><div className="community-group-card-body"><span className="community-role">{g.currentUserRole?`${g.currentUserRole.toLowerCase()} · Joined`:"Suggested community"}</span><h3>{g.name}</h3><p>{g.description||"Connect with local members, share updates and discover upcoming activities."}</p><ul><li><span className="material-icons">location_on</span>{[g.city,g.state,g.country].filter(Boolean).join(", ")||"Online"}</li><li><span className="material-icons">group</span>{g.memberCount} {g.memberCount===1?"member":"members"}</li></ul><div className="community-card-actions"><Link to={`/community/groups/${g.slug}`}>View community</Link>{!g.currentUserRole&&<button onClick={async()=>{await communityApi.joinGroup(g.id);await reload()}}>Join</button>}</div></div></article>)}{!groups.length&&<div className="community-state">No groups found.</div>}</div>}
function EventCards({events,register}:{events:CommunityEvent[];register?:boolean}){return <div className="community-cards">{events.map(e=><article key={e.id}><span>{e.eventMode}</span><h3>{e.title}</h3><p>{new Date(e.startAtUtc).toLocaleString()} · {e.city||e.venueName||"Online"}</p>{register&&<button onClick={()=>communityApi.registerEvent(e.id,"Community guest")}>RSVP</button>}</article>)}{!events.length&&<div className="community-state">No upcoming events.</div>}</div>}
function PostCards({posts}:{posts:CommunityPost[]}){return <div className="community-feed">{posts.map(p=><article key={p.id}><small>{p.authorName}</small><h3>{p.title}</h3><p>{p.body}</p><button onClick={()=>communityApi.react(p.id)}>♡ {p.reactionCount}</button><span>{p.commentCount} comments</span></article>)}{!posts.length&&<div className="community-state">No posts yet.</div>}</div>}
function Form({submit,children,label}:{submit:(f:FormData)=>Promise<void>;children:React.ReactNode;label:string}){const [saving,setSaving]=useState(false),[formError,setFormError]=useState("");return <form className="community-form" onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;setSaving(true);setFormError("");try{await submit(new FormData(form));form.reset()}catch(error){setFormError(error instanceof Error?error.message:"Unable to complete this action. Please try again.")}finally{setSaving(false)}}}>{children}{formError&&<p className="community-error" role="alert">{formError}</p>}<button type="submit" disabled={saving}>{saving?"Sending…":label}</button></form>}
function CreateGroup({done,cancel}:{done:()=>Promise<void>;cancel:()=>void}){return <Form label="Create group" submit={async f=>{await communityApi.createGroup({name:f.get("name"),description:f.get("description"),visibility:f.get("visibility"),city:f.get("city"),state:f.get("state"),country:f.get("country")});await done()}}><label>Group name<input name="name" required minLength={3} placeholder="Example: Novi Telugu Families"/></label><div className="community-location-fields"><label>Country<input name="country" required placeholder="United States"/></label><label>State / Province<input name="state" required placeholder="Michigan"/></label><label>City<input name="city" required placeholder="Novi"/></label></div><label>Visibility<select name="visibility"><option value="PUBLIC">Public — anyone can discover</option><option value="PRIVATE">Private — members only</option><option value="INVITE_ONLY">Invite only</option></select></label><label>Description<textarea name="description" required minLength={10} placeholder="Tell members what this group is about…"/></label><div className="community-modal-actions"><button type="button" className="community-secondary-button" onClick={cancel}>Cancel</button><button type="submit">Create group</button></div></Form>}
function CreatePost({groups,done}:{groups:CommunityGroup[];done:()=>Promise<void>}){return <Form label="Publish post" submit={async f=>{await communityApi.createPost({groupId:Number(f.get("groupId")),postType:"TEXT",body:f.get("body")});await done()}}><select name="groupId" required>{groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><textarea name="body" required placeholder="Share with your community…"/></Form>}
function GroupPicker({groups,onPick}:{groups:CommunityGroup[];onPick:(id:number)=>void}){return <select className="community-picker" onChange={e=>onPick(Number(e.target.value))}>{groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select>}
function StartDirect({contacts,done}:{contacts:CommunityGroupMember[];done:()=>Promise<void>}){return <Form label="Start chat" submit={async f=>{await communityApi.startDirect(Number(f.get("userId")));await done()}}><label className="community-field-label" htmlFor="chat-contact">Choose a community member</label><select id="chat-contact" name="userId" required defaultValue=""><option value="" disabled>Select member</option>{contacts.map(contact=><option value={contact.userId} key={contact.userId}>{contact.displayName} · {contact.role.toLowerCase()}</option>)}</select>{!contacts.length&&<small>Join a community to find members.</small>}</Form>}
function SendMessage({id,done}:{id:number;done:()=>Promise<void>}){return <Form label="Send" submit={async f=>{await communityApi.sendMessage(id,String(f.get("body")));await done()}}><input name="body" required placeholder="Write a message"/></Form>}
function CreateEvent({done}:{done:()=>Promise<void>}){return <Form label="Create event" submit={async f=>{const start=new Date(String(f.get("start")));await communityApi.createEvent({title:f.get("title"),eventMode:"IN_PERSON",country:f.get("country"),state:f.get("state"),city:f.get("city"),timeZone:"UTC",startAtUtc:start.toISOString(),endAtUtc:new Date(start.getTime()+7200000).toISOString(),currency:"USD"});await done()}}><input name="title" required minLength={3} placeholder="Event title"/><input name="country" required placeholder="Country"/><input name="state" required placeholder="State / Province"/><input name="city" required placeholder="City"/><input name="start" type="datetime-local" required/></Form>}
function CreateRegistry(){const [result,setResult]=useState("");return <><h2>Gift registry</h2><Form label="Create registry" submit={async f=>{const x=await communityApi.createRegistry({title:f.get("title"),description:f.get("description"),visibility:f.get("visibility")});setResult(`Registry created: ${JSON.stringify(x)}`)}}><input name="title" required placeholder="Registry title"/><select name="visibility"><option>PRIVATE</option><option>INVITEES</option><option>PUBLIC</option></select><textarea name="description" placeholder="Description"/></Form>{result&&<p>{result}</p>}</>}
function ObjectCards({items,empty}:{items:Record<string,unknown>[];empty:string}){return <div className="community-cards">{items.map((x,i)=><article key={String(x.id??i)}><h3>{String(x.title??x.notificationType??"Community item")}</h3><p>{String(x.body??x.status??"")}</p></article>)}{!items.length&&<div className="community-state">{empty}</div>}</div>}
function InvitationCards({items}:{items:Record<string,unknown>[]}){return <div className="community-cards">{items.map((item,index)=><article key={String(item.id??index)}><span>{String(item.invitationType||"Invitation")}</span><h3>{String(item.title)}</h3><p>{String(item.status)} · {String(item.visibility)}</p><Link to={`/community/invitations/manage/${String(item.id)}`}>Manage guests</Link></article>)}{!items.length&&<div className="community-state">No invitations yet.</div>}</div>}
function Profile(){const [me,setMe]=useState<{displayName:string;publicId:string}>();useEffect(()=>{import("../api/communityApi").then(x=>x.enterCommunity()).then(setMe)},[]);return <article className="community-profile"><span className="material-icons">account_circle</span><h2>{me?.displayName||"Loading…"}</h2><p>Community ID: {me?.publicId}</p><small>Your Community identity is isolated from legacy business tables.</small></article>}
