import { useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import UserHomeHeader from "../../home/ui/UserHomeHeader";
import HomeFooterSection from "../../home/ui/HomeFooterSection";
import { communityApi, type CommunityInvitationDetail } from "../api/communityApi";
import "./communityPortal.css";

export default function InvitationManagePage() {
  const id=Number(useParams().id);const [invitation,setInvitation]=useState<CommunityInvitationDetail>(),[guests,setGuests]=useState<Record<string,unknown>[]>([]),[guestToken,setGuestToken]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(true),[adding,setAdding]=useState(false);
  async function load(){setBusy(true);try{const [detail,list]=await Promise.all([communityApi.invitation(id),communityApi.invitationGuests(id)]);setInvitation(detail);setGuests(list.items)}finally{setBusy(false)}}
  useEffect(()=>{if(id)void load()},[id]);
  async function addGuest(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);setAdding(true);try{const result=await communityApi.addInvitationGuest(id,{name:form.get("name"),email:form.get("email")||undefined,phone:form.get("phone")||undefined,householdName:form.get("householdName")||undefined,householdSize:Number(form.get("householdSize")),allowedPlusOnes:Number(form.get("plusOnes")),functionIds:invitation?.functions.map(item=>item.id)||[]});setGuestToken(result.guestToken);formElement.reset();await load()}finally{setAdding(false)}}
  async function remind(guestId?:number){await communityApi.scheduleInvitationReminder(id,{guestId,channel:"IN_APP",scheduledAtUtc:new Date(Date.now()+60000).toISOString()});setMessage(guestId?"Guest reminder scheduled.":"Reminder scheduled for all guests.")}
  const accepted=guests.filter(guest=>guest.rsvpStatus==="ACCEPTED").length,declined=guests.filter(guest=>guest.rsvpStatus==="DECLINED").length,pending=guests.length-accepted-declined,attending=guests.reduce((sum,guest)=>sum+Number(guest.attendingCount||0),0);
  return <><UserHomeHeader hideAddAction/><main className="community-portal invitation-manage"><header><div><span>Invitation operations</span><h1>{invitation?.title||"Invitation"}</h1><p>{invitation?.invitationType?.replace(/_/g," ")} · {invitation?.status} · {invitation?.visibility}</p></div><Link to="/community/invitations">← Back to invitations</Link></header>{busy?<div className="community-state">Loading invitation…</div>:<section className="invitation-manage-workspace">
    <div className="invitation-manage-stats"><Stat icon="groups" value={guests.length} label="Invited guests"/><Stat icon="how_to_reg" value={accepted} label="Accepted" tone="green"/><Stat icon="schedule" value={pending} label="Awaiting RSVP" tone="amber"/><Stat icon="event_seat" value={attending} label="Attending" tone="purple"/></div>
    <section className="invitation-functions-panel"><header><div><span className="material-icons">event</span><div><h2>Event schedule</h2><p>{invitation?.functions.length||0} function{invitation?.functions.length===1?"":"s"} planned</p></div></div></header><div className="invitation-timeline">{invitation?.functions.map((item,index)=><article key={item.id}><div className="invitation-date-box"><b>{new Date(item.startAtUtc).toLocaleDateString(undefined,{day:"2-digit"})}</b><span>{new Date(item.startAtUtc).toLocaleDateString(undefined,{month:"short"})}</span></div><div><small>FUNCTION {index+1}</small><h3>{item.name}</h3><p><span className="material-icons">schedule</span>{new Date(item.startAtUtc).toLocaleString()}</p><p><span className="material-icons">location_on</span>{item.venueName||item.address||"Venue pending"}</p></div></article>)}</div></section>
    <section className="invitation-guests-panel"><div className="invitation-panel-heading"><div><h2>Guest list</h2><p>Add invitees, track RSVPs and schedule reminders.</p></div><button onClick={()=>remind()}><span className="material-icons">notifications_active</span>Remind all</button></div>
      <form className="invitation-guest-form" onSubmit={addGuest}><label>Guest name<input name="name" required placeholder="Full name"/></label><label>Email<input name="email" type="email" placeholder="name@example.com"/></label><label>Phone<input name="phone" placeholder="Phone number"/></label><label>Household<input name="householdName" placeholder="Family name"/></label><label>Household size<input name="householdSize" type="number" min="1" defaultValue="1"/></label><label>Plus ones<input name="plusOnes" type="number" min="0" defaultValue="0"/></label><button disabled={adding}><span className="material-icons">person_add</span>{adding?"Adding…":"Add guest"}</button></form>
      {guestToken&&<div className="invitation-token"><span className="material-icons">key</span><div><strong>Guest access token created</strong><p>Share this securely with the guest.</p><code>{guestToken}</code></div></div>}{message&&<p className="invitation-success">✓ {message}</p>}
      <div className="invitation-guest-grid">{guests.map((guest,index)=>{const status=String(guest.rsvpStatus||"PENDING");return <article key={String(guest.id??index)}><div className="invitation-guest-avatar">{String(guest.name||"G").charAt(0)}</div><div className="invitation-guest-info"><div><h3>{String(guest.name)}</h3><span className={`rsvp-${status.toLowerCase()}`}>{status}</span></div><p>{String(guest.householdName||guest.email||"Individual guest")}</p><small>{Number(guest.attendingCount||0)} attending · {Number(guest.allowedPlusOnes||0)} plus ones allowed</small></div><button onClick={()=>remind(Number(guest.id))} title="Schedule reminder"><span className="material-icons">notifications</span></button></article>})}{!guests.length&&<div className="invitation-empty"><span className="material-icons">person_add</span><h3>No guests added yet</h3><p>Use the form above to build your guest list.</p></div>}</div>
    </section>
  </section>}</main><HomeFooterSection/></>;
}
function Stat({icon,value,label,tone="blue"}:{icon:string;value:number;label:string;tone?:string}){return <article className={`tone-${tone}`}><span className="material-icons">{icon}</span><div><strong>{value}</strong><small>{label}</small></div></article>}
