import { useEffect, useState } from "react";
import { decideAdditionalWork, getCustomerAdditionalWork, getProviderAdditionalWork, proposeAdditionalWork, type AdditionalWorkProposal } from "../api/servicesMarketplaceApi";

export function ProviderAdditionalWork({ bookingId, status }: { bookingId: string; status: string }) {
  const [items, setItems] = useState<AdditionalWorkProposal[]>([]); const [message, setMessage] = useState("");
  async function load() { setItems(await getProviderAdditionalWork(bookingId)); } useEffect(() => { void load(); }, [bookingId]);
  async function submit(form: HTMLFormElement) { const f = new FormData(form); try { await proposeAdditionalWork(bookingId, { idempotencyKey: crypto.randomUUID(), reason: String(f.get("reason") || ""), notes: String(f.get("notes") || ""), proofPublicId: String(f.get("proof") || "") || undefined, lines: [{ lineType: String(f.get("lineType")), description: String(f.get("description") || ""), quantity: Number(f.get("quantity")), durationMinutes: Number(f.get("duration")) || undefined, unitPrice: Number(f.get("unitPrice")) }] }); form.reset(); await load(); setMessage("Additional-work quote sent for customer approval."); } catch { setMessage("Proposal was not accepted. Check service policy, amount, and fields."); } }
  return <section><h4>Additional work</h4>{status === "IN_PROGRESS" ? <form onSubmit={(e) => { e.preventDefault(); void submit(e.currentTarget); }}><select name="lineType"><option value="SERVICE_LABOR">Additional service/labor</option><option value="PART_MATERIAL">Part/material</option></select><input name="description" required placeholder="Description" /><input name="quantity" required min="0.01" step="0.01" type="number" placeholder="Quantity" /><input name="duration" min="1" type="number" placeholder="Duration minutes" /><input name="unitPrice" required min="0" step="0.01" type="number" placeholder="Unit price" /><input name="reason" required placeholder="Reason" /><textarea name="notes" placeholder="Notes" /><input name="proof" placeholder="Optional proof photo ID" /><button>Send approval request</button></form> : null}{items.map((x) => <p key={x.publicId}>{x.reason} · {x.currencyCode} {x.totalAmount.toFixed(2)} · {x.status}</p>)}{message ? <p role="status">{message}</p> : null}</section>;
}

export function CustomerAdditionalWork({ bookingId }: { bookingId: string }) {
  const [items, setItems] = useState<AdditionalWorkProposal[]>([]); const [total, setTotal] = useState<number>();
  async function load() { const x = await getCustomerAdditionalWork(bookingId); setItems(x.proposals); setTotal(x.finalPayableTotal); } useEffect(() => { void load(); }, [bookingId]);
  async function decide(id: string, approve: boolean) { await decideAdditionalWork(bookingId, id, approve, approve ? "CUSTOMER_APPROVED" : "CUSTOMER_REJECTED"); await load(); }
  return <section><h4>Additional work</h4>{items.map((x) => <article key={x.publicId}><strong>{x.reason}</strong>{x.lines.map((l, i) => <p key={i}>{l.description}: {x.currencyCode} {l.totalAmount.toFixed(2)}</p>)}<p>Total: {x.currencyCode} {x.totalAmount.toFixed(2)} · {x.status}</p>{x.status === "PENDING" ? <div><button onClick={() => void decide(x.publicId, true)}>Approve</button><button onClick={() => void decide(x.publicId, false)}>Reject</button></div> : null}</article>)}{total !== undefined ? <strong>Current payable total: {total.toFixed(2)}</strong> : null}</section>;
}
