import { useEffect, useState } from "react";
import { completeProviderJob, confirmCustomerCompletion, downloadServicesInvoice, getCustomerCompletion, getProviderCompletion, updateCompletionChecklist, type ServicesInvoice } from "../api/servicesMarketplaceApi";

async function openInvoice(invoice: ServicesInvoice) { const blob = await downloadServicesInvoice(invoice.publicId); const url = URL.createObjectURL(blob); window.open(url, "_blank", "noopener,noreferrer"); window.setTimeout(() => URL.revokeObjectURL(url), 60000); }
export function ProviderCompletion({ bookingId, status, rowVersion }: { bookingId: string; status: string; rowVersion: string }) {
  const [data, setData] = useState<Awaited<ReturnType<typeof getProviderCompletion>>>(); const [notes, setNotes] = useState(""); const [message, setMessage] = useState(""); async function load() { setData(await getProviderCompletion(bookingId)); } useEffect(() => { void load(); }, [bookingId]);
  async function finish() { try { await completeProviderJob(bookingId, notes, rowVersion, crypto.randomUUID()); await load(); setMessage("Job completed and invoice issued."); } catch { setMessage("Completion prerequisites are not satisfied. Resolve the highlighted controls and refresh."); } }
  return <section><h4>Controlled completion</h4>{data?.checklist.map((x) => <label key={x.publicId}><input type="checkbox" checked={x.isCompleted} onChange={(e) => void updateCompletionChecklist(bookingId, x.publicId, e.target.checked).then(load)} /> {x.title}{x.isRequired ? " *" : ""}</label>)}{status === "IN_PROGRESS" ? <><textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Required final notes" /><button onClick={() => void finish()}>Complete job</button></> : null}{data?.invoice ? <button onClick={() => void openInvoice(data.invoice!)}>Download {data.invoice.invoiceNumber}</button> : null}{message ? <p role="status">{message}</p> : null}</section>;
}
export function CustomerCompletion({ bookingId }: { bookingId: string }) { const [confirmed, setConfirmed] = useState(false); const [invoice, setInvoice] = useState<ServicesInvoice | null>(); async function load() { const x = await getCustomerCompletion(bookingId); setConfirmed(x.confirmed); setInvoice(x.invoice); } useEffect(() => { void load(); }, [bookingId]); return <section><h4>Job completion</h4>{!confirmed ? <button onClick={() => void confirmCustomerCompletion(bookingId).then(load)}>Confirm work completion</button> : <p>Completion confirmed.</p>}{invoice ? <><p>{invoice.invoiceNumber} · {invoice.currencyCode} {invoice.totalAmount.toFixed(2)}</p><button onClick={() => void openInvoice(invoice)}>Download invoice</button></> : null}</section>; }
