import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { getProviderOnboarding, startProviderOnboarding, submitProviderOnboarding, updateProviderOnboarding } from "../api/servicesMarketplaceApi";
import type { ProviderProfile } from "../api/servicesMarketplaceApi";
import "./providerOnboarding.css";
import { ProviderVerificationPanel } from "./ProviderVerificationPanel";
import { ProviderQualificationsPanel } from "./ProviderQualificationsPanel";
import { ProviderAvailabilityPanel } from "./ProviderAvailabilityPanel";

export default function ProviderOnboarding() {
  const [profile, setProfile] = useState<ProviderProfile | null>(null); const [busy, setBusy] = useState(true); const [message, setMessage] = useState("");
  useEffect(() => { void getProviderOnboarding().then(setProfile).catch(() => setProfile(null)).finally(() => setBusy(false)); }, []);
  async function start() { setBusy(true); setMessage(""); try { setProfile(await startProviderOnboarding()); } catch { setMessage("Onboarding could not be started."); } finally { setBusy(false); } }
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); setMessage(""); try { setProfile(await updateProviderOnboarding({ providerType: String(f.get("providerType")) as "INDIVIDUAL" | "BUSINESS", displayName: String(f.get("displayName")), businessName: String(f.get("businessName")) || null, email: String(f.get("email")), phone: String(f.get("phone")), addressReference: null, addressLine: String(f.get("addressLine")) || null, locality: String(f.get("locality")) || null, administrativeArea: String(f.get("administrativeArea")) || null, postalCode: String(f.get("postalCode")) || null, countryCode: String(f.get("countryCode")) || null, profileSummary: String(f.get("profileSummary")) || null, termsAcknowledged: f.get("termsAcknowledged") === "on", sopAcknowledged: f.get("sopAcknowledged") === "on" })); setMessage("Progress saved."); } catch { setMessage("Please check the required fields and try again."); } finally { setBusy(false); } }
  async function submit() { setBusy(true); setMessage(""); try { setProfile(await submitProviderOnboarding()); setMessage("Submitted for review."); } catch { setMessage("Complete all required fields and acknowledgements before submitting."); } finally { setBusy(false); } }
  if (busy && !profile) return <div className="services-state">Loading provider onboarding…</div>;
  if (!profile) return <main className="provider-onboarding"><header><span>CHAO DESI PARTNERS</span><h1>Become a Service Professional</h1><p>Create your provider profile and submit it for operations review.</p></header>{message && <div className="services-alert">{message}</div>}<button className="provider-primary" onClick={() => void start()} disabled={busy}>Start onboarding</button></main>;
  const editable = profile.status === "DRAFT" || profile.status === "REJECTED";
  return <main className="provider-onboarding"><header><span>PROVIDER ONBOARDING</span><h1>{profile.displayName || "Complete your profile"}</h1><p>Status: <b>{profile.status.replace(/_/g, " ")}</b></p><div className="provider-progress"><i style={{ width: `${profile.completionPercent}%` }} /><span>{profile.completionPercent}% complete</span></div></header>
    {profile.decisionReason ? <div className="services-alert"><b>Action required:</b> {profile.decisionReason}</div> : null}{message ? <div className="services-alert">{message}</div> : null}
    <form className="provider-form" onSubmit={save}><label>Professional type<select name="providerType" defaultValue={profile.providerType} disabled={!editable}><option value="INDIVIDUAL">Individual professional</option><option value="BUSINESS">Business / company</option></select></label><label>Display name<input name="displayName" defaultValue={profile.displayName} required maxLength={200} disabled={!editable} /></label><label>Business name<input name="businessName" defaultValue={profile.businessName || ""} maxLength={200} disabled={!editable} /></label><label>Email<input name="email" type="email" defaultValue={profile.email} required disabled={!editable} /></label><label>Phone<input name="phone" defaultValue={profile.phone} required disabled={!editable} /></label><label>Address<input name="addressLine" defaultValue={profile.addressLine || ""} disabled={!editable} /></label><label>City/locality<input name="locality" defaultValue={profile.locality || ""} disabled={!editable} /></label><label>State/province<input name="administrativeArea" defaultValue={profile.administrativeArea || ""} disabled={!editable} /></label><label>Postal code<input name="postalCode" defaultValue={profile.postalCode || ""} disabled={!editable} /></label><label>Country code<input name="countryCode" defaultValue={profile.countryCode || ""} maxLength={3} required disabled={!editable} /></label><label className="provider-wide">Profile summary<textarea name="profileSummary" defaultValue={profile.profileSummary || ""} maxLength={2000} disabled={!editable} /></label><label className="provider-check"><input type="checkbox" name="termsAcknowledged" defaultChecked={profile.termsAcknowledged} disabled={!editable} /> I acknowledge the provider terms (placeholder version).</label><label className="provider-check"><input type="checkbox" name="sopAcknowledged" defaultChecked={profile.sopAcknowledged} disabled={!editable} /> I acknowledge the operating SOP (placeholder version).</label>{editable ? <div className="provider-actions"><button type="submit" disabled={busy}>Save progress</button><button type="button" onClick={() => void submit()} disabled={busy || profile.completionPercent < 100}>Submit for review</button></div> : null}</form>
    <ProviderVerificationPanel /><ProviderQualificationsPanel /><ProviderAvailabilityPanel />{profile.history.length ? <section className="provider-history"><h2>Status history</h2>{profile.history.map((x, i) => <div key={`${x.createdAtUtc}-${i}`}><b>{x.toStatus.replace(/_/g, " ")}</b><span>{new Date(x.createdAtUtc).toLocaleString()}</span>{x.reason ? <p>{x.reason}</p> : null}</div>)}</section> : null}</main>;
}
