import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { addProviderAvailabilityPeriod, addProviderCoverage, addProviderWeeklySchedule, deleteProviderAvailabilityPeriod, deleteProviderWeeklySchedule, getProviderAvailability, getProviderAvailabilityOptions, saveProviderSupplySettings } from "../api/servicesMarketplaceApi";
import type { AvailabilityOptions, ProviderAvailability } from "../api/servicesMarketplaceApi";
import "./providerAvailability.css";

const days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export function ProviderAvailabilityPanel() {
  const [data, setData] = useState<ProviderAvailability | null>(null); const [options, setOptions] = useState<AvailabilityOptions>({ services: [], areas: [] }); const [message, setMessage] = useState("");
  async function load() { const [a, o] = await Promise.all([getProviderAvailability(), getProviderAvailabilityOptions()]); setData(a); setOptions(o); }
  useEffect(() => { void load().catch(() => setMessage("Availability could not be loaded.")); }, []);
  async function perform(action: () => Promise<unknown>, ok: string) { try { await action(); await load(); setMessage(ok); } catch { setMessage("The availability change was rejected. Check ranges and overlaps."); } }
  async function settings(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await perform(() => saveProviderSupplySettings({ timeZoneId: String(f.get("timeZoneId")), isOnline: f.get("isOnline") === "on", minimumLeadTimeMinutes: Number(f.get("lead")), maximumAdvanceBookingDays: Number(f.get("advance")) }), "Supply settings saved."); }
  async function coverage(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const number = (k: string) => String(f.get(k) || "") ? Number(f.get(k)) : null; await perform(() => addProviderCoverage({ serviceId: String(f.get("serviceId")), areaId: String(f.get("areaId")), originLatitude: number("latitude"), originLongitude: number("longitude"), maximumRadiusKm: number("radius"), isActive: true }), "Coverage saved."); }
  async function weekly(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await perform(() => addProviderWeeklySchedule({ serviceId: String(f.get("serviceId")) || null, dayOfWeek: Number(f.get("day")), startLocalTime: String(f.get("start")), endLocalTime: String(f.get("end")), isActive: true }), "Working hours added."); }
  async function period(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await perform(() => addProviderAvailabilityPeriod({ serviceId: String(f.get("serviceId")) || null, periodType: String(f.get("type")), startAtUtc: new Date(String(f.get("start"))).toISOString(), endAtUtc: new Date(String(f.get("end"))).toISOString(), reason: String(f.get("reason")) || null }), "Availability exception added."); }
  if (!data) return <section className="provider-history"><h2>Coverage and availability</h2><p>{message || "Loading…"}</p></section>;
  return <section className="provider-history provider-availability"><h2>Coverage and availability</h2><p>Weekly hours use your selected timezone. Exceptions are converted and stored in UTC.</p>{data.isAdminSuspended ? <div className="services-alert"><b>Availability suspended:</b> {data.adminSuspensionReason}</div> : null}{message ? <div className="services-alert">{message}</div> : null}
    <form onSubmit={settings}><h3>Supply settings</h3><input name="timeZoneId" defaultValue={data.timeZoneId || Intl.DateTimeFormat().resolvedOptions().timeZone} required /><input name="lead" type="number" min="0" max="10080" defaultValue={data.minimumLeadTimeMinutes} /><input name="advance" type="number" min="1" max="365" defaultValue={data.maximumAdvanceBookingDays} /><label><input name="isOnline" type="checkbox" defaultChecked={data.isOnline} /> Go online / accept new work</label><button>Save settings</button></form>
    <form onSubmit={coverage}><h3>Service coverage</h3><select name="serviceId" required><option value="">Service</option>{options.services.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select><select name="areaId" required><option value="">Area</option>{options.areas.map((x) => <option value={x.publicId} key={x.publicId}>{x.name} · {x.countryCode}</option>)}</select><input name="latitude" type="number" step="0.000001" placeholder="Origin latitude (optional)" /><input name="longitude" type="number" step="0.000001" placeholder="Origin longitude (optional)" /><input name="radius" type="number" step="0.1" min="0.1" max="1000" placeholder="Maximum radius km (optional)" /><button>Save coverage</button></form>
    <div className="availability-list">{data.coverage.map((x) => <span key={x.publicId}>{x.serviceName} · {x.areaName}{x.maximumRadiusKm ? ` · ${x.maximumRadiusKm} km` : ""}</span>)}</div>
    <form onSubmit={weekly}><h3>Weekly working hours</h3><select name="serviceId"><option value="">All qualified services</option>{options.services.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select><select name="day">{days.map((x, i) => <option value={i} key={x}>{x}</option>)}</select><input name="start" type="time" required /><input name="end" type="time" required /><button>Add hours</button></form>
    <div className="availability-list">{data.weekly.map((x) => <span key={x.publicId}>{days[x.dayOfWeek]} · {x.startLocalTime.slice(0,5)}–{x.endLocalTime.slice(0,5)} <button onClick={() => void perform(() => deleteProviderWeeklySchedule(x.publicId), "Hours removed.")}>Remove</button></span>)}</div>
    <form onSubmit={period}><h3>Break, blackout, time off, or available override</h3><select name="serviceId"><option value="">All services</option>{options.services.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select><select name="type"><option>BREAK</option><option>BLACKOUT</option><option>TIME_OFF</option><option>AVAILABLE_OVERRIDE</option></select><input name="start" type="datetime-local" required /><input name="end" type="datetime-local" required /><input name="reason" placeholder="Reason" /><button>Add exception</button></form>
    <div className="availability-list">{data.periods.map((x) => <span key={x.publicId}>{x.periodType} · {new Date(x.startAtUtc).toLocaleString()}–{new Date(x.endAtUtc).toLocaleString()} {x.isAdminOverride ? "· Admin" : <button onClick={() => void perform(() => deleteProviderAvailabilityPeriod(x.publicId), "Exception removed.")}>Remove</button>}</span>)}</div>
  </section>;
}
