import { useEffect, useState } from "react";
import { downloadProviderDocument, getProviderDocumentAccess, getProviderVerification, uploadProviderVerification } from "../api/servicesMarketplaceApi";
import type { VerificationRequirement } from "../api/servicesMarketplaceApi";
import "./providerVerification.css";

export function ProviderVerificationPanel() {
  const [items, setItems] = useState<VerificationRequirement[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  async function load() { setItems(await getProviderVerification()); }
  useEffect(() => { void load().catch(() => setMessage("Verification requirements could not be loaded.")); }, []);
  async function upload(item: VerificationRequirement, file: File | undefined, expiry?: string) { if (!file) return; setBusy(item.id); setMessage(""); try { await uploadProviderVerification(item.id, file, expiry); await load(); } catch { setMessage("Upload rejected. Check the allowed file type, size, content, and expiry date."); } finally { setBusy(""); } }
  async function view(id: string) { try { const access = await getProviderDocumentAccess(id); const blob = await downloadProviderDocument(access.token); const url = URL.createObjectURL(blob); window.open(url, "_blank", "noopener,noreferrer"); window.setTimeout(() => URL.revokeObjectURL(url), 60000); } catch { setMessage("Secure document access could not be created."); } }
  return <section className="provider-history"><h2>Verification requirements</h2><p>Documents are private and available only through short-lived authorized access.</p>{message ? <div className="services-alert">{message}</div> : null}{items.length === 0 ? <p>No verification requirements currently apply.</p> : items.map((x) => { const replace = ["MISSING","REJECTED","EXPIRED"].includes(x.status); return <article className="provider-verification" key={x.id}><div><h3>{x.displayName}</h3><b>{x.status.replace(/_/g, " ")}</b><p>{x.description}</p>{x.rejectionReason ? <p className="services-alert">{x.rejectionReason}</p> : null}<small>Allowed: {x.allowedExtensions.join(", ")} · Maximum {(x.maxFileSizeBytes / 1048576).toFixed(0)} MB</small>{x.expiresAtUtc ? <p>Expires: {new Date(x.expiresAtUtc).toLocaleDateString()}</p> : null}{x.document ? <p>{x.document.fileName} · scan {x.document.scanStatus} <button type="button" onClick={() => void view(x.document!.id)}>Secure view</button></p> : null}</div>{replace ? <VerificationUpload item={x} busy={busy === x.id} upload={upload} /> : null}</article>; })}</section>;
}
function VerificationUpload({ item, busy, upload }: { item: VerificationRequirement; busy: boolean; upload: (item: VerificationRequirement, file?: File, expiry?: string) => void }) { const [file, setFile] = useState<File>(); const [expiry, setExpiry] = useState(""); return <div className="verification-upload"><input aria-label={`Upload ${item.displayName}`} type="file" accept={item.allowedExtensions.join(",")} onChange={(e) => setFile(e.target.files?.[0])} />{item.expiryRequired ? <input aria-label="Document expiry" type="date" value={expiry} onChange={(e) => setExpiry(e.target.value)} /> : null}<button type="button" disabled={busy || !file || (item.expiryRequired && !expiry)} onClick={() => void upload(item, file, expiry)}>{item.status === "MISSING" ? "Upload" : "Replace document"}</button></div>; }
