import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { completeProviderTraining, getMarketplaceServices, getProviderQualifications, getProviderTraining, saveProviderQualification } from "../api/servicesMarketplaceApi";
import type { ProviderQualification, ProviderTraining } from "../api/servicesMarketplaceApi";
import "./providerQualifications.css";

export function ProviderQualificationsPanel() {
  const [items, setItems] = useState<ProviderQualification[]>([]); const [services, setServices] = useState<{ id: string; name: string }[]>([]); const [training, setTraining] = useState<ProviderTraining[]>([]); const [selected, setSelected] = useState(""); const [message, setMessage] = useState("");
  async function load() { setItems(await getProviderQualifications()); }
  useEffect(() => { void Promise.all([load(), getMarketplaceServices().then((x) => setServices(x.map((y) => ({ id: y.service.id, name: y.service.name }))))]).catch(() => setMessage("Qualifications could not be loaded.")); }, []);
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const serviceId = String(f.get("serviceId")); try { await saveProviderQualification(serviceId, { experienceYears: Number(f.get("experienceYears")) || null, skillsSummary: String(f.get("skillsSummary")) || null, certificationSummary: String(f.get("certificationSummary")) || null }); await load(); setMessage("Service qualification submitted for review."); } catch { setMessage("Qualification could not be saved."); } }
  async function openTraining(serviceId: string) { setSelected(serviceId); try { setTraining(await getProviderTraining(serviceId)); } catch { setMessage("Training modules could not be loaded."); } }
  async function complete(id: string) { try { await completeProviderTraining(id); if (selected) setTraining(await getProviderTraining(selected)); await load(); } catch { setMessage("This module requires an approved assessment result or could not be completed."); } }
  return <section className="provider-history"><h2>Skills and service eligibility</h2>{message ? <div className="services-alert">{message}</div> : null}<form className="qualification-form" onSubmit={save}><select name="serviceId" required><option value="">Choose a service</option>{services.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="experienceYears" type="number" min="0" max="80" placeholder="Years of experience" /><textarea name="skillsSummary" maxLength={2000} placeholder="Relevant skills and experience" /><textarea name="certificationSummary" maxLength={2000} placeholder="Certification summary (documents belong in Verification)" /><button type="submit">Add or update skill</button></form>
    {items.map((x) => <article className="provider-verification" key={x.publicId}><div><h3>{x.serviceName}</h3><b>{x.status}</b><p>{x.eligibility.isEligible ? "Eligible for job matching" : x.eligibility.reason}</p>{x.eligibility.unsatisfiedRequirements.length ? <ul>{x.eligibility.unsatisfiedRequirements.map((r) => <li key={r}>{r}</li>)}</ul> : null}{x.eligibilityReason ? <small>Admin reason: {x.eligibilityReason}</small> : null}</div><button type="button" onClick={() => void openTraining(x.serviceId)}>Training & SOPs</button></article>)}
    {selected ? <div className="qualification-training"><h3>Training modules</h3>{training.length === 0 ? <p>No active training modules.</p> : training.map((x) => <article key={x.publicId}><h4>{x.title} · v{x.version}</h4><p>{x.description}</p>{x.contentBody ? <div>{x.contentBody}</div> : null}{x.contentUrl ? <a href={x.contentUrl} target="_blank" rel="noreferrer">Open {x.contentType.toLowerCase()}</a> : null}<p>{x.isCompleted ? "Completed" : x.passingScore != null ? `Assessment required · passing score ${x.passingScore}` : "Acknowledgement required"}</p>{!x.isCompleted && x.passingScore == null ? <button onClick={() => void complete(x.publicId)}>Acknowledge and complete</button> : null}</article>)}</div> : null}</section>;
}
